---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())
library("lme4")
library("lmerTest")
library("emmeans")
library("ggResidpanel")

options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```


Look at bioyield and transportation costs
```{r mean_data, dependson = "create_soilpad"}
## How much is it going to cost to realize the INRS? How much to achieve wildlife goals?
envOutcome_CostSum <- practSumBIO %>%
  #group_by(practice) %>%
  group_by(FBndID) %>%
  #group_by(radial,biomass) %>%
  summarize(n       = n(),
            MLRA = max(MLRA),
            HUC12 = max(HUC12),
            radial = max(radial),
            IWAP = list(unique(IWAP)),
            practice = list(unique(practice)),
            
            ## Cost summary per field
            opArea_ha = sum(opArea_ha),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            sumDCcp = sum(DirectCost_CP),
            sumTCcp = sum(TotalCost_CP),

            ## Bio yield summary
            sum_BioMg = sum(bioYield_Mg),
            DC_BioMg = sum_BioMg / sumDC,
            DCcp_BioMg = sum_BioMg / sumDCcp,
            TC_BioMg = sum_BioMg / sumTC,
            TCcp_BioMg = sum_BioMg / sumTCcp,
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #BioTC_Mg_med = median(TC_MgBio, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #BioTCcp_Mg_med = median(TCcp_MgBio, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## Energy potential summary
            sumEnergyPot = sum(energyPot),
            DC_MMBtu = sumDC / sumEnergyPot,
            DCcp_MMBtu = sumDCcp / sumEnergyPot,
            TC_MMBtu = sumTC / sumEnergyPot,
            TCcp_MMBtu = sumTCcp / sumEnergyPot,
            #engPot_med = median(energyPot, na.rm = TRUE),
            #Q1_engPot = quantile(energyPot, probs = c(0.25)),
            #Q3_engPot = quantile(energyPot, probs = c(0.75)),
            #engPotTC_med = median(TC_enPot, na.rm = TRUE),
            #Q1TC_enPot = quantile(TC_enPot, probs = c(0.25)),
            #Q3TC_enPot = quantile(TC_enPot, probs = c(0.75)),
            #engPotTCcp_med = median(TCcp_enPot, na.rm = TRUE),
            #Q1TCcp_enPot = quantile(TCcp_enPot, probs = c(0.25)),
            #Q3TCcp_enPot = quantile(TCcp_enPot, probs = c(0.75)),
            
            ## Wildlife ummary
            sum_WHha = sum(opArea_ha),
            DC_WHha = sumDC / sum_WHha,
            DCcp_WHha = sumDCcp / sum_WHha,
            TC_WHha = sumTC / sum_WHha,
            TCcp_WHha = sumTCcp/ sum_WHha,
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #WHTC_ha_med = median(TC_haWH, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #WHTCcp_ha_med = median(TCcp_haWH, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## CO2 summary
            sumCO2 = sum(CO2red),
            DC_CO2 = sumDC / sumCO2,
            DCcp_CO2 = sumDCcp / sumCO2,
            TC_CO2 = sumTC / sumCO2,
            TCcp_CO2 = sumTCcp / sumCO2,
            #CO2red_med = median(CO2red, na.rm = TRUE),
            #Q1_CO2red = quantile(CO2red, probs = c(0.25)),
            #Q3_CO2red = quantile(CO2red, probs = c(0.75)),
            #CO2TC_Mg_med = median(TC_MgCO2, na.rm=TRUE),
            #Q1_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.25)),
            #Q3_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.75)),
            #CO2TCcp_Mg_med = median(TCcp_MgCO2, na.rm=TRUE),
            #Q1_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.25)),
            #Q3_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.75)),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),
            DC_N2Ored = sumDC / sumN2Ored,
            DCcp_N2Ored = sumDCcp / sumN2Ored,
            TC_N2Ored = sumTC / sumN2Ored,
            TCcp_N2Ored = sumTCcp / sumN2Ored,
            #N2Ored_med = median(N2Ored, na.rm=TRUE),
            #Q1_N2Ored = quantile(N2Ored, probs = c(0.25)),
            #Q3_N2Ored = quantile(N2Ored, probs = c(0.75)),
            #N2OTC_Mg_med = median(TC_MgN2O, na.rm=TRUE),
            #Q1_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.25)),
            #Q3_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.75)),
            #N2OTCcp_Mg_med = median(TCcp_MgN2O, na.rm=TRUE),
            #Q1_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.25)),
            #Q3_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.75)),
            
            # NO3 load summary
            sumNO3red = sum(cpNO3ldRedkg, na.rm = TRUE),
            DC_NO3red = sumDC / sumNO3red,
            DCcp_NO3red = sumDCcp / sumNO3red,
            TC_NO3red = sumTC / sumNO3red,
            TCcp_NO3red = sumTCcp / sumNO3red,
            #NO3red_med = median(cpNO3ldRedkg, na.rm = TRUE),
            #Q1_NO3red = quantile(cpNO3ldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3red = quantile(cpNO3ldRedkg, probs = c(0.75), na.rm = TRUE),
            #NO3TC_kg_med = median(TC_kgNO3, na.rm = TRUE),
            #Q1_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.75), na.rm = TRUE),
            #NO3TCcp_kg_med = median(TCcp_kgNO3, na.rm = TRUE),
            #Q1_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            sumSEDred = sum(cpSEDldRedkg, na.rm = TRUE),
            DC_SEDred = sumDC / sumSEDred,
            DCcp_SEDred = sumDCcp / sumSEDred,
            TC_SEDred = sumTC / sumSEDred,
            TCcp_SEDred = sumTCcp / sumSEDred,
            #SEDred_med = median(cpSEDldRedkg, na.rm = TRUE),
            #Q1_SEDred = quantile(cpSEDldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDred = quantile(cpSEDldRedkg, probs = c(0.75), na.rm = TRUE),
            #SEDTC_kg_med = median(TC_kgSED, na.rm = TRUE),
            #Q1_SEDTC_kg = quantile(TC_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTC_kg = quantile(TC_kgSED, probs = c(0.75), na.rm = TRUE),
            #SEDTCcp_kg_med = median(TCcp_kgSED, na.rm = TRUE),
            #Q1_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.75), na.rm = TRUE),
            
            ## This analysis is only meaningful if we have a monetized value, or rate, that can be used and then multiple
            ## the total reduction by that value and divide by total cost. 
            #NSB_DC_ha = (DC_BioMg+DC_MMBtu+DC_WHha+DC_CO2+DC_N2Ored+DC_NO3red+DC_SEDred)-sumDC,
            #NSB_DCcp_ha = (DCcp_BioMg+DCcp_MMBtu+DCcp_WHha+DCcp_CO2+DCcp_N2Ored+DCcp_NO3red+DCcp_SEDred)-sumDCcp,
            #NSB_TC_ha = (TC_BioMg+TC_MMBtu+TC_WHha+TC_CO2+TC_N2Ored+TC_NO3red+TC_SEDred)-sumTC,
            #NSB_TCcp_ha = (TCcp_BioMg+TCcp_MMBtu+TCcp_WHha+TCcp_CO2+TCcp_N2Ored+TCcp_NO3red+TCcp_SEDred)-sumTCcp,
            #BCR_DC = (DC_BioMg+DC_MMBtu+DC_WHha+DC_CO2+DC_N2Ored+DC_NO3red+DC_SEDred)/sumDC,
            #BCR_DCcp = (DCcp_BioMg+DCcp_MMBtu+DCcp_WHha+DCcp_CO2+DCcp_N2Ored+DCcp_NO3red+DCcp_SEDred)/sumDCcp,
            #BCR_TC = (TC_BioMg+TC_MMBtu+TC_WHha+TC_CO2+TC_N2Ored+TC_NO3red+TC_SEDred)/sumTC,
            #BCR_TCcp = (TCcp_BioMg+TCcp_MMBtu+TCcp_WHha+TCcp_CO2+TCcp_N2Ored+TCcp_NO3red+TCcp_SEDred)/sumTCcp,
            #MCE_DC = sumDC / (DC_BioMg+DC_MMBtu+DC_WHha+DC_CO2+DC_N2Ored+DC_NO3red+DC_SEDred),
            #MCE_DCcp = sumDCcp / (DCcp_BioMg+DCcp_MMBtu+DCcp_WHha+DCcp_CO2+DCcp_N2Ored+DCcp_NO3red+DCcp_SEDred),
            #MCE_TC = sumTC / (TC_BioMg+TC_MMBtu+TC_WHha+TC_CO2+TC_N2Ored+TC_NO3red+TC_SEDred),
            #MCE_TCcp = sumTCcp / (TCcp_BioMg+TCcp_MMBtu+TCcp_WHha+TCcp_CO2+TCcp_N2Ored+TCcp_NO3red+TCcp_SEDred),
            
            .groups = "drop")

write_csv(envOutcome_CostSum,"envOutcome_byField.csv")

envOutcome_FBsummary <- envOutcome_CostSum %>%
  group_by(FBndID) %>%
  summarize(sum_opArea = sum(opArea_ha),
            opArea_med = median(opArea_ha, na.rm = TRUE),
            Q1_opArea = quantile(opArea_ha, probs = c(0.25)),
            Q3_opArea = quantile(opArea_ha, probs = c(0.75)),
            n       = n(),
            #MLRA = max(MLRA),
            #HUC12 = max(HUC12),
            #IWAP = max(IWAP),
            #practice = list(unique(practice)),

            ## Bio yield summary
            sum_BioMg2 = sum(sum_BioMg),
            BioMg_med = median(sum_BioMg, na.rm = TRUE),
            Q1_BioMg = quantile(sum_BioMg, probs = c(0.25)),
            Q3_BioMg = quantile(sum_BioMg, probs = c(0.75)),
            
            ## Energy potential summary
            #sumEnergyPot2 = sum(sumEnergyPot),
            engPot_med = median(sumEnergyPot, na.rm = TRUE),
            Q1_engPot = quantile(sumEnergyPot, probs = c(0.25)),
            Q3_engPot = quantile(sumEnergyPot, probs = c(0.75)),
            
            ## Cost summary per field
            sumDC2 = sum(sumDC),
            sumDC_med = median(sumDC, na.rm = TRUE),
            Q1_sumDC = quantile(sumDC, probs = c(0.25)),
            Q3_sumDC = quantile(sumDC, probs = c(0.75)),
            #sumOC = sum(adjOCost),
            sumTC2 = sum(sumTC),
            sumTC_med = median(sumTC, na.rm = TRUE),
            Q1_sumTC = quantile(sumTC, probs = c(0.25)),
            Q3_sumTC = quantile(sumTC, probs = c(0.75)),
            sumDCcp2 = sum(sumDCcp),
            sumDCcp_med = median(sumDCcp, na.rm = TRUE),
            Q1_sumDCcp = quantile(sumDCcp, probs = c(0.25)),
            Q3_sumDCcp = quantile(sumDCcp, probs = c(0.75)),
            sumTCcp2 = sum(sumTCcp),
            sumTCcp_med = median(sumTCcp, na.rm = TRUE),
            Q1_sumTCcp = quantile(sumTCcp, probs = c(0.25)),
            Q3_sumTCcp = quantile(sumTCcp, probs = c(0.75)),
            
            ## CO2 summary
            #sumCO22 = sum(sumCO2),
            CO2red_med = median(sumCO2, na.rm = TRUE),
            Q1_CO2red = quantile(sumCO2, probs = c(0.25)),
            Q3_CO2red = quantile(sumCO2, probs = c(0.75)),
            
            ## N2O summary
            #sumN2Ored2 = sum(sumN2Ored),
            N2Ored_med = median(sumN2Ored, na.rm=TRUE),
            Q1_N2Ored = quantile(sumN2Ored, probs = c(0.25)),
            Q3_N2Ored = quantile(sumN2Ored, probs = c(0.75)),
            
            # NO3 load summary
            #sumNO3red2 = sum(sumNO3red, na.rm = TRUE),
            NO3red_med = median(sumNO3red, na.rm = TRUE),
            Q1_NO3red = quantile(sumNO3red, probs = c(0.25), na.rm = TRUE),
            Q3_NO3red = quantile(sumNO3red, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            #sumSEDred2 = sum(sumSEDred, na.rm = TRUE),
            SEDred_med = median(sumSEDred, na.rm = TRUE),
            Q1_SEDred = quantile(sumSEDred, probs = c(0.25), na.rm = TRUE),
            Q3_SEDred = quantile(sumSEDred, probs = c(0.75), na.rm = TRUE),

            .groups = "drop")

write_csv(envOutcome_FBsummary,"envOutcome_biosummary.csv")

travel_envOutcomes <- full_join(envOutcome_CostSum, fbSieversRoute)

travel_Sum <- travel_envOutcomes %>%
  #group_by(radial) %>%
  group_by(FBndID,radial) %>%
  drop_na(Total_Kilometers) %>%
  summarize(AOI = "supplyshed",
            rnd_dist = 2*Total_Kilometers,
            BioMg = sum(sum_BioMg),
            DC = sum(sumDC),
            DCcp = sum(sumDCcp),
            TC = sum(sumTC),
            TCcp = sum(sumTCcp),
            Ctruck = sum_BioMg*(2*Total_Kilometers)*0.265, # $ per field. trucking cost. 2026 ISU Custom Rate survey. Transportation coefficient = "haul round bales by truck or trailer per bale per mile", assuming 0.68 Mg of hay in a bale (Hart etal. 2015).
            Ctruck_Mg = (2*Total_Kilometers)*0.265,
            Chand = sum_BioMg*4.7794, # $ per field. 2026 ISU Custom Rate survey. Loading/unloading = "moving large round bales to storage per bale", assuming 0.68 Mg of hay in a bale. Coefficients are assumed to be fixed cost. 
            Ctotal = Ctruck + Chand, # trucking + handling costs per field.
            Ctotal_Mg = (Ctruck + Chand) / sum_BioMg, # transportation cost per Mg of biomass harvested from a field
            #Ctotal_Mg_km = Ctotal / sum_BioMg / rnd_dist,
            Cdeliv = Ctotal + sumDC, # cost per field for biomass
            Cdeliv_Mg = Cdeliv / sum_BioMg # production + transportation cost per Mg delivered from a field
            #Cdeliv_Mg_km = Cdeliv / sum_BioMg / rnd_dist
            #Ccpdeliv = Ctotal + sumDCcp, # cost per field for biomass and structural components
            #Ccpdeliv_Mg = Ccpdeliv / sum_BioMg,
            #Ccpdeliv_Mg_km = Ccpdeliv / sum_BioMg / rnd_dist,
            #sum_hectares = sum(opArea_ha),
            #sum_bioYield = sum(sumbioYield),
            #sum_enPot = sum(sumEnergyPot),
            #dist_med = median(Total_Kilometers, na.rm = TRUE),
            #Q1_SEDred = quantile(Total_Kilometers, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDred = quantile(Total_Kilometers, probs = c(0.75), na.rm = TRUE),
            #dist_mean = mean((2*Total_Kilometers), na.rm = TRUE),
            #dist_sd = sd((2*Total_Kilometers), na.rm = TRUE),
            #dist_lb = (dist_mean-dist_sd),
            #dist_ub = (dist_mean+dist_sd), 
            
            #fuel_cost = median(fuel_cost),
            #lbr_cost = median(lbr_cost),
            #trans_cost = median(trans_cost))
            #dist_min = min(Total_Kilometers, na.rm = TRUE),
            #dist_max = max(Total_Kilometers, na.rm = TRUE),
            #time_med = median(Total_TruckTravelTime, na.rm = TRUE),
            #Q1_time = quantile(Total_TruckTravelTime, probs = c(0.25), na.rm = TRUE),
            #Q3_time = quantile(Total_TruckTravelTime, probs = c(0.75), na.rm = TRUE))
            #fuelCost_mean = mean(fuel_cost, na.rm = TRUE),
            #fuelCost_sd = sd(fuel_cost, na.rm = TRUE),
            #fuelCost_lb = (fuelCost_mean-fuelCost_sd),
            #fuelCost_ub = (fuelCost_mean+fuelCost_sd),
            #fuelCost_min = min(trk_cost, na.rm = TRUE),
            #fuelCost_max = max(trk_cost, na.rm = TRUE),
            #lbrCost_mean = mean(lbr_cost, na.rm = TRUE),
            #lbrCost_sd = sd(lbr_cost, na.rm = TRUE),
            #lbrCost_lb = (lbrCost_mean-lbrCost_sd),
            #lbrCost_ub = (lbrCost_mean+lbrCost_sd),
            #lbrCost_min = min(lbr_cost, na.rm = TRUE),
            #lbrCost_max = max(lbr_cost, na.rm = TRUE),
            #transCost_mean = mean(trans_cost, na.rm = TRUE),
            #transCost_sd = sd(trans_cost, na.rm = TRUE),
            #transCost_lb = (transCost_mean-transCost_sd),
           #transCost_ub = (transCost_mean+transCost_sd))
            #transCost_min = min(trans_cost, na.rm = TRUE),
            #transCost_max = max(trans_cost, na.rm = TRUE))
  )

Ctravel_radial <- travel_Sum %>%
  group_by(radial) %>%
  #group_by(AOI) %>%
  summarize(mean_dist = mean(rnd_dist, na.rm = TRUE),
            #sd_dist = sd(rnd_dist),
            med_dist = median(rnd_dist, na.rm = TRUE),
            Q1_dist = quantile(rnd_dist, probs = c(0.25), na.rm = TRUE),
            Q3_dist = quantile(rnd_dist, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctruck = mean(Ctruck, na.rm = TRUE),
            #sd_Ctruck = sd(Ctruck),
            med_Ctruck = median(Ctruck_Mg, na.rm = TRUE),
            Q1_Ctruck = quantile(Ctruck_Mg, probs = c(0.25), na.rm = TRUE),
            Q3_Ctruck = quantile(Ctruck_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Chand = mean(Chand, na.rm = TRUE),
            sum_Chand = sum(Chand, na.rm = TRUE),
            #sd_Chand = sd(Chand),
            med_Chand = median(Chand, na.rm = TRUE),
            Q1_Chand = quantile(Chand, probs = c(0.25), na.rm = TRUE),
            Q3_Chand = quantile(Chand, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctotal = mean(Ctotal, na.rm = TRUE),
            sum_Ctotal = sum(Ctotal, na.rm = TRUE),
            sd_Ctotal = sd(Ctotal, na.rm = TRUE),
            med_Ctotal = median(Ctotal, na.rm = TRUE),
            Q1_Ctotal = quantile(Ctotal, probs = c(0.25), na.rm = TRUE),
            Q3_Ctotal = quantile(Ctotal, probs = c(0.75), na.rm = TRUE),
           
            mean_Ctotal_Mg = mean(Ctotal_Mg, na.rm = TRUE),
            #sd_Ctotal_Mg = sd(Ctotal_Mg),
            med_Ctotal_Mg = median(Ctotal_Mg, na.rm = TRUE),
            Q1_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.25), na.rm = TRUE),
            Q3_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Cdeliv = mean(Cdeliv, na.rm = TRUE),
            sum_Cdeliv = sum(Cdeliv, na.rm = TRUE),
            #sd_Cdeliv = sd(Cdeliv),
            med_Cdeliv = median(Cdeliv, na.rm = TRUE),
            Q1_Cdeliv = quantile(Cdeliv, probs = c(0.25), na.rm = TRUE),
            Q3_Cdeliv = quantile(Cdeliv, probs = c(0.75), na.rm = TRUE),
            
            mean_Cdeliv_Mg = mean(Cdeliv_Mg, na.rm = TRUE),
            #sd_Cdeliv_Mg =sd(Cdeliv_Mg),
            med_Cdeliv_Mg = median(Cdeliv_Mg, na.rm = TRUE),
            Q1_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.25), na.rm = TRUE),
            Q3_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.75), na.rm = TRUE)
  ) %>%
  drop_na(radial)

write_csv(Ctravel_radial,"travelcosts_byRad.csv")


```

```{r mean_data, dependson = "create_soilpad"}
mxMg_Cost = travel_Sum %>%
  drop_na(radial) %>%
  #filter(stabCorn != "Stable High") %>%
  ggplot(aes(x = factor(radial) , y = (Ctruck / sum_BioMg))) +
  geom_boxplot() +
  theme(axis.text.x = element_text(vjust = 0.5, hjust = 1, face= "bold"), axis.title.y = element_text(face = "bold")) +
  labs(x = "Radial Supplyshed (km)", y = "Delivered Cost Rate ($/Mg)")
  #geom_point()
mxMg_Cost

df_travel <- mean_travel %>%
  pivot_longer(cols = c(msumDC,mCtruck, mChand), 
               names_to = "activity", 
               values_to = "byFieldCost")

mean_travel <- travel_Sum %>%
  group_by(radial) %>%
  summarize(mCtruck = mean(Ctruck, na.rm = TRUE),
            #mChand = mean(Chand, na.rm = TRUE),
            #msumDC = mean(sumDC, na.rm = TRUE),
            count = n())

mxCdeliv = travel_Sum %>%
  drop_na(radial) %>%
  #ggplot(aes(fill=activity, y=byFieldCost, x=factor(radial))) + 
  ggplot(aes(y=Ctruck/sum_BioMg, x=factor(radial))) + 
  #facet_grid(.~radial) +
  #geom_bar(position="stack", stat="identity")
  geom_boxplot()
  #geom_jitter(width = 0.2, alpha = 0.5, colour = "black", fill = "black")
  #geom_errorbar(aes(x=factor(radial), ymin = med_Ctruck-Q1_Ctruck, ymax = med_Ctruck+Q3_Ctruck))
mxCdeliv

df_HUC12outcome <- envOutcome_CostSum %>%
  pivot_longer(cols = c(opArea_ha,sum_BioMg, sumCO2, sumEnergyPot, sumN2Ored, sumNO3red, sumSEDred, sumOC, sumTC), 
               names_to = "outcome", 
               values_to = "value")

HUC12_count <- envOutcome_CostSum %>%
  group_by(HUC12) %>%
  summarize(aoi = "supplyshed",
            count = n(),
            t_opArea_ha = sum(opArea_ha),
            t_Bio = sum(sum_BioMg)/t_opArea_ha, 
            t_CO2 = sum(sumCO2)/t_opArea_ha, 
            t_MMBtu = sum(sumEnergyPot)/t_opArea_ha, 
            t_N2O = sum(sumN2Ored)/t_opArea_ha, 
            t_NO3 = sum(sumNO3red)/t_opArea_ha, 
            t_sed = sum(sumSEDred)/t_opArea_ha, 
            t_OC = sum(sumOC)/t_opArea_ha, 
            t_TC = sum(sumTC)/t_opArea_ha)

df_HUC12 <- HUC12_count %>%
  pivot_longer(cols = count:t_TC, 
               names_to = "outcome", 
               values_to = "value")

msumOC <- df_HUC12outcome %>%
  filter(outcome == "sumCO2") %>%
  #drop_na(radial) %>%
  ggplot(aes(y=value, x=HUC12)) + 
  #geom_point(aes(color=HUC12))
  geom_bar() +
  geom_hline(yintercept = median(value)) +
  facet_wrap(~outcome, ncol=1, scales = "free")
  
  #geom_jitter(width = 0.2, alpha = 0.5)
  #geom_errorbar(aes(x=factor(radial), ymin = med_Ctruck-Q1_Ctruck, ymax = med_Ctruck+Q3_Ctruck))
msumOC
ggsave("sum_out_haHUC12.png", msumOC, width = 60, height = 60, limitsize = FALSE)

```

