---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup_HUC12}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())

library("factoextra")
library("cluster")
library("ggrepel")
library("fmsb")
library("stringr")
library("ggplot2")

options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```

```{r}
sessionInfo()
```

Look at bioyield and transportation costs
```{r ws_data, cache.extra=tools::md5sum("../data/raw/HUC12_list.csv")}

wsArea <- read_csv("../data/raw/HUC12_list.csv") %>%
  mutate(supArea_ha = supArea_ac *0.404686,
         area_ha = areaacres*0.404686,
         HUC12 = str_pad(huc12, width = 12, pad = "0"))

# IMPORTANT:
# All outcomes in this analysis occur inside the 32-km supplyshed.
# Therefore, landscape-scale metrics should use the area of each HUC12
# that falls inside the 32-km supplyshed, rather than the full HUC12 area.
#
# HUC12_list.csv should contain `supplyshed_area_ha`, calculated from the
# spatial intersection of the HUC12 boundaries and the 32-km supplyshed.
# This keeps the denominator consistent with the spatial extent of the
# outcomes being summarized.
#
# If `supplyshed_area_ha` has not yet been added to HUC12_list.csv, the
# analysis is intentionally stopped rather than silently using full-HUC12
# area and producing inconsistent normalized metrics.
if (!"supArea_ha" %in% names(wsArea)) {
  stop(
    "HUC12_list.csv must contain `supplyshed_area_ha`, representing the ",
    "area of each HUC12 within the 32-km supplyshed. Calculate this by ",
    "intersecting the HUC12 boundaries with the 32-km supplyshed boundary."
  )
}

wsArea <- wsArea %>%
  select(HUC12, area_ha, supArea_ha)


```
## Read in data

```{r, child="create_datasets.Rmd"}
```


```{r envOutcomes, dependson="create_df"}

## How much is it going to cost to realize the INRS? How much to achieve wildlife goals?
envOutcome_CostSum <- practSumBIO %>%
  group_by(FBndID) %>%
  summarize(n       = n(),
            MLRA = max(MLRA),
            HUC12 = max(HUC12),
            radial = max(radial),
            IWAP = list(unique(IWAP)),
            practice = list(unique(practice)),
            
            ## Cost summary per field
            opArea_ha = sum(opArea_ha),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            sumDCcp = sum(DirectCost_CP),
            sumTCcp = sum(TotalCost_CP),
            
            ## Bio yield summary
            sum_BioMg = sum(bioYield_Mg),
            DC_BioMg = sum_BioMg / sumDC,
            DCcp_BioMg = sum_BioMg / sumDCcp,
            TC_BioMg = sum_BioMg / sumTC,
            TCcp_BioMg = sum_BioMg / sumTCcp,
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #BioTC_Mg_med = median(TC_MgBio, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #BioTCcp_Mg_med = median(TCcp_MgBio, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## Energy potential summary
            sumEnergyPot = sum(energyPot),
            DC_MMBtu = sumDC / sumEnergyPot,
            DCcp_MMBtu = sumDCcp / sumEnergyPot,
            TC_MMBtu = sumTC / sumEnergyPot,
            TCcp_MMBtu = sumTCcp / sumEnergyPot,
            #engPot_med = median(energyPot, na.rm = TRUE),
            #Q1_engPot = quantile(energyPot, probs = c(0.25)),
            #Q3_engPot = quantile(energyPot, probs = c(0.75)),
            #engPotTC_med = median(TC_enPot, na.rm = TRUE),
            #Q1TC_enPot = quantile(TC_enPot, probs = c(0.25)),
            #Q3TC_enPot = quantile(TC_enPot, probs = c(0.75)),
            #engPotTCcp_med = median(TCcp_enPot, na.rm = TRUE),
            #Q1TCcp_enPot = quantile(TCcp_enPot, probs = c(0.25)),
            #Q3TCcp_enPot = quantile(TCcp_enPot, probs = c(0.75)),
            
            ## Wildlife Summary
            sum_patch_ha = sum(patch_ha),
            sum_lin_ha = sum(lin_ha),
            sum_wh_ha = sum(lin_ha) + sum(patch_ha),
            sum_rye_ha = sum(rye_ha),
            DC_pha = sumDC / sum(patch_ha),
            DC_lha = sumDC / sum(lin_ha),
            DC_wha = sumDC / sum(lin_ha) + sum(patch_ha),
            DCcp_pha = sumDCcp / sum(patch_ha),
            DCcp_lha = sumDCcp / sum(lin_ha),
            DCcp_wha = sumDCcp / sum(lin_ha) + sum(patch_ha),
            TC_pha = sumTC / sum(patch_ha),
            TC_lha = sumTC / sum(lin_ha),
            TC_wha = sumTC / sum(lin_ha) + sum(patch_ha),
            TCcp_pha = sumTCcp / sum(patch_ha),
            TCcp_lha = sumTCcp / sum(lin_ha),
            TCcp_wha = sumTCcp / sum(lin_ha) + sum(patch_ha),
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #WHTC_ha_med = median(TC_haWH, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #WHTCcp_ha_med = median(TCcp_haWH, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## CO2 summary
            sumCO2 = sum(CO2red),
            DC_CO2 = sumDC / sumCO2,
            DCcp_CO2 = sumDCcp / sumCO2,
            TC_CO2 = sumTC / sumCO2,
            TCcp_CO2 = sumTCcp / sumCO2,
            #CO2red_med = median(CO2red, na.rm = TRUE),
            #Q1_CO2red = quantile(CO2red, probs = c(0.25)),
            #Q3_CO2red = quantile(CO2red, probs = c(0.75)),
            #CO2TC_Mg_med = median(TC_MgCO2, na.rm=TRUE),
            #Q1_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.25)),
            #Q3_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.75)),
            #CO2TCcp_Mg_med = median(TCcp_MgCO2, na.rm=TRUE),
            #Q1_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.25)),
            #Q3_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.75)),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),
            DC_N2Ored = sumDC / sumN2Ored,
            DCcp_N2Ored = sumDCcp / sumN2Ored,
            TC_N2Ored = sumTC / sumN2Ored,
            TCcp_N2Ored = sumTCcp / sumN2Ored,
            #N2Ored_med = median(N2Ored, na.rm=TRUE),
            #Q1_N2Ored = quantile(N2Ored, probs = c(0.25)),
            #Q3_N2Ored = quantile(N2Ored, probs = c(0.75)),
            #N2OTC_Mg_med = median(TC_MgN2O, na.rm=TRUE),
            #Q1_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.25)),
            #Q3_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.75)),
            #N2OTCcp_Mg_med = median(TCcp_MgN2O, na.rm=TRUE),
            #Q1_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.25)),
            #Q3_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.75)),
            
            # NO3 load summary
            sumNO3red = sum(cpNO3ldRedkg, na.rm = TRUE),
            DC_NO3red = sumDC / sumNO3red,
            DCcp_NO3red = sumDCcp / sumNO3red,
            TC_NO3red = sumTC / sumNO3red,
            TCcp_NO3red = sumTCcp / sumNO3red,
            #NO3red_med = median(cpNO3ldRedkg, na.rm = TRUE),
            #Q1_NO3red = quantile(cpNO3ldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3red = quantile(cpNO3ldRedkg, probs = c(0.75), na.rm = TRUE),
            #NO3TC_kg_med = median(TC_kgNO3, na.rm = TRUE),
            #Q1_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.75), na.rm = TRUE),
            #NO3TCcp_kg_med = median(TCcp_kgNO3, na.rm = TRUE),
            #Q1_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            sumSEDred = sum(cpSEDldRedkg, na.rm = TRUE),
            DC_SEDred = sumDC / sumSEDred,
            DCcp_SEDred = sumDCcp / sumSEDred,
            TC_SEDred = sumTC / sumSEDred,
            TCcp_SEDred = sumTCcp / sumSEDred,
            #SEDred_med = median(cpSEDldRedkg, na.rm = TRUE),
            #Q1_SEDred = quantile(cpSEDldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDred = quantile(cpSEDldRedkg, probs = c(0.75), na.rm = TRUE),
            #SEDTC_kg_med = median(TC_kgSED, na.rm = TRUE),
            #Q1_SEDTC_kg = quantile(TC_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTC_kg = quantile(TC_kgSED, probs = c(0.75), na.rm = TRUE),
            #SEDTCcp_kg_med = median(TCcp_kgSED, na.rm = TRUE),
            #Q1_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.75), na.rm = TRUE),
            )

#write_csv(envOutcome_CostSum,"envOutcome_byField.csv")
```

```{r travelOutcomes, dependson="envOutcome"}

travel_envOutcomes <- full_join(envOutcome_CostSum, fbSieversRoute)
profit_trvl_env <- full_join(AvgProfit, travel_envOutcomes) %>%
  drop_na(n)

travel_HUC12Sum <- travel_envOutcomes %>%
  #group_by(radial) %>%
  group_by(FBndID,HUC12) %>%
  drop_na(Total_Kilometers) %>%
  summarize(AOI = "supplyshed",
            opArea = sum(opArea_ha),
            n       = n(),
            ## Bio yield summary
            BioMg = sum(sum_BioMg),
            
            ## Energy potential summary
            EnergyPot = sum(sumEnergyPot),

            ## Cost summary per field
            DC = sum(sumDC),
            OC = sum(sumOC),
            TC = sum(sumTC),
            DCcp = sum(sumDCcp),
            TCcp = sum(sumTCcp),
            
            ## Wildlife habitat summary
            patch = sum(sum_patch_ha),
            lin = sum(sum_lin_ha),
            prairie = sum(sum_wh_ha),
            rye = sum(sum_rye_ha),

            ## CO2 summary
            CO2 = sum(sumCO2),
            
            ## N2O summary
            N2Ored = sum(sumN2Ored),

            # NO3 load summary
            NO3red = sum(sumNO3red, na.rm = TRUE),

            ## Sediment load summary
            SEDred = sum(sumSEDred, na.rm = TRUE),
            
            Ctruck = sum_BioMg*(2*Total_Kilometers)*0.265, # $ per field. trucking cost. 2026 ISU Custom Rate survey. Transportation coefficient = "haul round bales by truck or trailer per bale per mile", assuming 0.68 Mg of hay in a bale (Hart etal. 2015).
            Ctruck_Mg = (2*Total_Kilometers)*0.265,
            Chand = sum_BioMg*4.7794, # $ per field. 2026 ISU Custom Rate survey. Loading/unloading = "moving large round bales to storage per bale", assuming 0.68 Mg of hay in a bale. Coefficients are assumed to be fixed cost. 
            Ctotal = Ctruck + Chand, # trucking + handling costs per field.
            rnd_dist = 2*Total_Kilometers,
            Ctotal_Mg = (Ctruck + Chand) / sum_BioMg, # transportation cost per Mg of biomass harvested from a field
            Ctotal_Mg_km = Ctotal / sum_BioMg / rnd_dist,
            Cdeliv = Ctotal + sumDC, # cost per field for biomass
            Cdeliv_Mg = Cdeliv / sum_BioMg, # production + transportation cost per Mg delivered from a field
            Cdeliv_Mg_km = Cdeliv / sum_BioMg / rnd_dist,
            Ccpdeliv = Ctotal + sumDCcp, # cost per field for biomass and structural components
            Ccpdeliv_Mg = Ccpdeliv / sum_BioMg,
            Ccpdeliv_Mg_km = Ccpdeliv / sum_BioMg / rnd_dist
            )
```

```{r HUC12data, dependson="envOutcome"}
## need to run both exploratory_yields and exploratory_profits to get the profit_yield dataframe.
profitHUC12 <- profit_yield %>% 
  filter(unprofit == "unprofitable") %>%
  group_by(HUC12) %>%
  summarize(sum_UNPha = sum(subArea_ha)) %>%
  drop_na()

ysHUC12 <- profit_yield %>%
  #filter(stabCorn == "Unstable") %>%
  filter(stabCorn != "Stable Low") %>%
  group_by(HUC12) %>%
  summarize(sum_UNSTha = sum(subArea_ha)) #%>%
  #drop_na()


```

```{r HUC12_travel, dependson="HUC12data"}
Ctravel_HUC12 <- travel_HUC12Sum %>%
  #group_by(radial) %>%
  group_by(HUC12) %>%
  summarize(sumOPha = sum(opArea),
            sumBioMg = sum(BioMg),
            
            ## Energy potential summary
            sumEnergyPot = sum(EnergyPot),
            sumDC = sum(DC),
            sumOC = sum(OC),
            sumTC = sum(TC),
            sumDCcp = sum(DCcp),
            sumTCcp = sum(TCcp),
            
            ## Wildlife habitat summary
            sumpatch = sum(patch),
            sumlin = sum(lin),
            sumprairie = sum(prairie),
            sumrye = sum(rye),
            
            ## CO2 summary
            sumCO2 = sum(CO2),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),

            # NO3 load summary
            sumNO3red = sum(NO3red, na.rm = TRUE),

            ## Sediment load summary
            sumSEDred = sum(SEDred, na.rm = TRUE),
            
            mean_dist = mean(rnd_dist, na.rm = TRUE),
            #sd_dist = sd(rnd_dist),
            #med_dist = median(rnd_dist, na.rm = TRUE),
            #Q1_dist = quantile(rnd_dist, probs = c(0.25), na.rm = TRUE),
            #Q3_dist = quantile(rnd_dist, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctruck = mean(Ctruck, na.rm = TRUE),
            sum_Ctruck = sum(Ctruck),
            mean_Ctruck = mean(Ctruck_Mg, na.rm=TRUE),
            #sd_Ctruck = sd(Ctruck),
            #med_Ctruck = median(Ctruck_Mg, na.rm = TRUE),
            #Q1_Ctruck = quantile(Ctruck_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctruck = quantile(Ctruck_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Chand = mean(Chand, na.rm = TRUE),
            sum_Chand = sum(Chand, na.rm = TRUE),
            #sd_Chand = sd(Chand),
            #med_Chand = median(Chand, na.rm = TRUE),
            #Q1_Chand = quantile(Chand, probs = c(0.25), na.rm = TRUE),
            #Q3_Chand = quantile(Chand, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctotal = mean(Ctotal, na.rm = TRUE),
            sum_Ctotal = sum(Ctotal, na.rm = TRUE),
            #sd_Ctotal = sd(Ctotal, na.rm = TRUE),
            #med_Ctotal = median(Ctotal, na.rm = TRUE),
            #Q1_Ctotal = quantile(Ctotal, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctotal = quantile(Ctotal, probs = c(0.75), na.rm = TRUE),
           
            mean_Ctotal_Mg = mean(Ctotal_Mg, na.rm = TRUE),
            #sd_Ctotal_Mg = sd(Ctotal_Mg),
            #med_Ctotal_Mg = median(Ctotal_Mg, na.rm = TRUE),
            #Q1_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Cdeliv = mean(Cdeliv, na.rm = TRUE),
            sum_Cdeliv = sum(Cdeliv, na.rm = TRUE),
            #sd_Cdeliv = sd(Cdeliv),
            #med_Cdeliv = median(Cdeliv, na.rm = TRUE),
            #Q1_Cdeliv = quantile(Cdeliv, probs = c(0.25), na.rm = TRUE),
            #Q3_Cdeliv = quantile(Cdeliv, probs = c(0.75), na.rm = TRUE),
            mean_Cdeliv_Mg = mean(Cdeliv_Mg, na.rm = TRUE),
            #sd_Cdeliv_Mg =sd(Cdeliv_Mg),
            #med_Cdeliv_Mg = median(Cdeliv_Mg, na.rm = TRUE),
            #Q1_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.75), na.rm = TRUE)
  )

#write_csv(Ctravel_radial,"travelcosts_byRad.csv")

```

```{r HUC12_summary, dependson="HUC12_travel"}
huc12_summary <- full_join(Ctravel_HUC12, wsArea)

huc12_summary <- wsArea %>%
  full_join(Ctravel_HUC12) %>%
  full_join(ysHUC12) %>%
  full_join(profitHUC12) %>%
  drop_na(HUC12,sumOPha) %>%
  replace_na(list(sum_UNSTha = 0)) ## 7 HUC12 watersheds had 0 subfields designated as unstable


huc12_df <- huc12_summary %>%
  mutate(
    # ----------------------------------------------------------
    # Landscape-scale metrics
    #
    # The denominator is the portion of each HUC12 within the
    # 32-km supplyshed (`area_ha`), so all outcomes and treatment
    # areas are expressed relative to the same spatial extent.
    # ----------------------------------------------------------
    per_treated = sumOPha / area_ha,
    per_patch = sumpatch / area_ha,
    per_lin = sumlin / area_ha,
    per_prairie = sumprairie / area_ha,
    per_rye = sumrye / area_ha,

    bio_Mg_ha = sumBioMg / area_ha,
    dccp_ha = sumDCcp / area_ha,

    ghg_ha = (sumCO2 + sumN2Ored) / area_ha,
    no3_ha = sumNO3red / area_ha,
    sed_ha = sumSEDred / area_ha,
    no3_red = sumNO3red/NO3_loadkg,
    sed_red = sumSEDred/sed_loadkg,
    
    
    stabLow_ha = sum_UNSTha / area_ha,
    unprofit_ha = sum_UNPha / area_ha,
    oc_ha = sumOC / area_ha,

    # ----------------------------------------------------------
    # Treatment-level performance metrics
    #
    # These are calculated per hectare treated and are kept
    # separate from the landscape-scale classification.
    # ----------------------------------------------------------
    no3_per_treated_ha = sumNO3red / sumOPha,
    sed_per_treated_ha = sumSEDred / sumOPha,
    ghg_per_treated_ha = (sumCO2 + sumN2Ored) / sumOPha,
    bio_per_treated_ha = sumBioMg / sumOPha,
    oc_per_treated_ha = sumOC / sumOPha,
    dccp_per_treated_ha = sumDCcp / sumOPha,
    tccp_per_treated_ha = sumTCcp / sumOPha,

    # Treatment composition, not efficiency
    prairie_share_treated = sumprairie / sumOPha,
    rye_share_treated = sumrye / sumOPha
  ) %>%
  filter(sumOPha > 0)

```

```{r multivariate, dependson="HUC12_summary"}
# ============================================================
# MULTIVARIATE HUC12 PLANNING CLASSIFICATION
# ============================================================
#
# The classification describes combinations of:
#   * treatment extent and composition,
#   * landscape-scale environmental outcomes,
#   * biomass production, and
#   * direct conservation investment.
#
# It is a classification step within the decision-support
# framework, not a universal ranking of HUC12s.
# ============================================================

huc12_planning <- huc12_df

# ------------------------------------------------------------
# 1. Variables used for the planning classification
#
# GHG is retained as an important output but is not used to
# define the classes because the current GHG estimates are
# strongly tied to practice extent/composition. N2O is included
# within ghg_ha and is therefore retained as an output rather
# than used as a separate clustering variable.
# ------------------------------------------------------------

cluster_vars <- huc12_planning %>%
  select(
    #per_treated,
    per_patch,
    per_lin,
    per_rye,
    no3_ha,
    sed_ha,
    bio_Mg_ha,
    ghg_ha
    #dccp_ha
  )

# Retain only HUC12s with complete classification data.
cluster_complete <- cluster_vars %>%
  drop_na()

huc12_cluster <- huc12_planning %>%
  filter(complete.cases(cluster_vars))

# Standardize variables because they are measured in different units.
cluster_scaled <- scale(cluster_complete)

```

```{r pca, dependson="multivariate"}
# ------------------------------------------------------------
# 2. Correlation and PCA diagnostics
#
# PCA is used here to understand variable structure and aid
# interpretation. Clustering is performed on all standardized
# classification variables rather than an arbitrary subset of
# principal components.
# ------------------------------------------------------------

cluster_cor <- cor(
  cluster_complete,
  use = "pairwise.complete.obs"
)

print(cluster_cor)

pca_model <- prcomp(
  cluster_scaled,
  center = FALSE,
  scale. = FALSE
)

summary(pca_model)

fviz_eig(
  pca_model,
  addlabels = TRUE
)

fviz_pca_var(
  pca_model,
  col.var = "contrib",
  repel = TRUE
)

# ------------------------------------------------------------
# 3. Evaluate candidate numbers of planning classes
# ------------------------------------------------------------

set.seed(123)

wss_plot <- fviz_nbclust(
  cluster_scaled,
  kmeans,
  method = "wss",
  k.max = 6,
  nstart = 100
)

sil_plot <- fviz_nbclust(
  cluster_scaled,
  kmeans,
  method = "silhouette",
  k.max = 6,
  nstart = 100
)

wss_plot
sil_plot

# Compare candidate solutions directly.
set.seed(123)

km2 <- kmeans(cluster_scaled, centers = 2, nstart = 100)
km3 <- kmeans(cluster_scaled, centers = 3, nstart = 100)
km4 <- kmeans(cluster_scaled, centers = 4, nstart = 100)
km5 <- kmeans(cluster_scaled, centers = 5, nstart = 100)

sil2 <- silhouette(km2$cluster, dist(cluster_scaled))
sil3 <- silhouette(km3$cluster, dist(cluster_scaled))
sil4 <- silhouette(km4$cluster, dist(cluster_scaled))
sil5 <- silhouette(km5$cluster, dist(cluster_scaled))

silhouette_summary <- tibble(
  k = 2:5,
  mean_silhouette = c(
    mean(sil2[, "sil_width"]),
    mean(sil3[, "sil_width"]),
    mean(sil4[, "sil_width"]),
    mean(sil5[, "sil_width"])
  ),
  min_silhouette = c(
    min(sil2[, "sil_width"]),
    min(sil3[, "sil_width"]),
    min(sil4[, "sil_width"]),
    min(sil5[, "sil_width"])
  )
)

print(silhouette_summary)

```

```{r cluster_analysis, dependson="pca"}

# ------------------------------------------------------------
# 4. Select the planning-class solution
#
# k = 3 is used as the working solution because three classes
# provide a digestible stakeholder-facing classification while
# retaining meaningful differentiation. This choice should be
# revisited after the revised variables and clipped-area
# denominator are applied, using silhouette performance,
# cluster size, and interpretability together.
# ------------------------------------------------------------

set.seed(123)
k <- 5

km_model <- kmeans(
  cluster_scaled,
  centers = k,
  nstart = 100
)

huc12_cluster$cluster <- factor(km_model$cluster)

# ------------------------------------------------------------
# 5. Summarize planning classes before assigning labels
#
# Cluster numbers are arbitrary. Inspect this table before
# assigning descriptive labels.
# ------------------------------------------------------------

cluster_summary <- huc12_cluster %>%
  group_by(cluster) %>%
  summarise(
    n = n(),

    mean_per_treated = mean(per_treated, na.rm = TRUE),
    mean_per_patch = mean(per_patch, na.rm = TRUE),
    mean_per_lin = mean(per_lin, na.rm = TRUE),
    mean_per_rye = mean(per_rye, na.rm = TRUE),

    mean_no3_ha = mean(no3_ha, na.rm = TRUE),
    mean_sed_ha = mean(sed_ha, na.rm = TRUE),
    mean_ghg_ha = mean(ghg_ha, na.rm = TRUE),
    mean_bio_Mg_ha = mean(bio_Mg_ha, na.rm = TRUE),
    mean_dccp_ha = mean(dccp_ha, na.rm = TRUE),
    mean_no3red = mean(no3_red),
    mean_sedred = mean(sed_red),

    .groups = "drop"
  )

print(cluster_summary)
write.csv(
  cluster_summary,
  "../data/tidy/cluster_summary.csv",
  row.names = FALSE
)

```

```{r planning_clusters, dependson="cluster_analysis"}
# ------------------------------------------------------------
# 6. Use the cluster solution as the planning classification
#
# Do not assign value-laden labels such as "best", "high
# opportunity", or "low quality". The classes are descriptive
# groupings and planners can interpret them according to their
# own objectives.
# ------------------------------------------------------------

huc12_planning <- huc12_cluster %>%
  mutate(
    Planning_Class = paste0("Planning class ", cluster)
  )

# Join the class back to the full HUC12 dataset.
huc12_planning <- huc12_df %>%
  left_join(
    huc12_planning %>%
      select(HUC12, cluster, Planning_Class),
    by = "HUC12"
  )

# ------------------------------------------------------------
# 7. Visualize planning classes
# ------------------------------------------------------------

fviz_cluster(
  km_model,
  data = cluster_scaled,
  geom = "point",
  ellipse.type = "convex",
  ggtheme = theme_minimal()
)

# ------------------------------------------------------------
# 8. Landscape-scale distributions by planning class
# ------------------------------------------------------------
facet_labels <- c(
  bio_Mg_ha   = "atop(Biomass~Yield,(Mg~ha^{-1}))",
  no3_ha      = "atop(NO[3]~Load~Red.,(Mg~ha^{-1}))",
  dccp_ha     = "atop(Direct~Cost,(USD~ha^{-1}))",
  sed_ha      = "atop(Sed.~Load~Red.,(Mg~ha^{-1}))",
  ghg_ha      = "atop(GHG~Red.,(Mg~CO[2]*e~ha^{-1}))",
  per_treated = "Treated~('%')",
  per_patch   = "Prairie~Patch~('%')",
  per_lin     = "Linear~Habitat~('%')",
  per_rye     = "Cereal~Rye~('%')"
)

huc12_planning %>%
  pivot_longer(cols = c(no3_ha,sed_ha,ghg_ha,per_treated,per_patch,per_lin,per_rye,bio_Mg_ha,dccp_ha
             #unprofit_ha,
             #stabLow_ha
    ),names_to = "Metric",values_to = "Value") %>%
  ggplot(aes(x = Planning_Class,y = Value,fill = Planning_Class)) +
  geom_boxplot() +
  facet_wrap(~ factor(Metric, c("no3_ha","sed_ha","ghg_ha","bio_Mg_ha","per_treated","per_rye","per_patch","per_lin","dccp_ha")), scales = "free_y",ncol = 2,,
             strip.position = "left",
             labeller = as_labeller(facet_labels, label_parsed)) +
  ylab(NULL) +
  theme_minimal() +
  theme(text = element_text(family = "serif", size = 9),
    axis.text.x = element_blank(),
    strip.background = element_blank(),
    strip.placement = "outside"
  ) +
  scale_fill_manual(values = c('#377EB8','#4DAF4A','#984EA3','#FF7F00','#FFFF33'), labels = c("Nutrient-Biomass Integration", "Limited Environmental Intervention","Moderate Multifunctional Outcomes","Water-Quality-Biomass Integration","Prairie-Habitat-Nutrient Integration"))

#write.csv(
#  huc12_planning,
#  "../data/tidy/huc12_planning_classes.csv",
#  row.names = FALSE
#)

```

```{r treatment_performance, dependson="planning_clusters"}
# ============================================================
# TREATMENT-PERFORMANCE ANALYSIS
# ============================================================
#
# These metrics answer a different question from the landscape
# classification: how do outcomes and implementation intensity
# compare per hectare actually treated?
# ============================================================

huc12_perf <- huc12_planning %>%
  #filter(sumOPha > 0) %>%
  mutate(
    # Environmental outcome per treated hectare
    no3_per_treated_ha = sumNO3red / sumOPha,
    sed_per_treated_ha = sumSEDred / sumOPha,
    ghg_per_treated_ha = (sumCO2 + sumN2Ored) / sumOPha,

    # Biomass production per treated hectare
    bio_per_treated_ha = sumBioMg / sumOPha,

    # Treatment composition
    prairie_share_treated = sumprairie / sumOPha,
    rye_share_treated = sumrye / sumOPha,

    # Direct conservation investment per treated hectare
    dccp_per_treated_ha = sumDCcp / sumOPha,
    tccp_per_treated_ha,
    
    #structural feasibility
    stabLow_ha,
    unprofit_ha
  )

# ------------------------------------------------------------
# 9. Summarize treatment performance by planning class
# ------------------------------------------------------------

performance_summary <- huc12_perf %>%
  group_by(Planning_Class) %>%
  summarise(
    n = n(),

    # Landscape extent
    mean_per_treated = mean(per_treated, na.rm = TRUE),

    # Environmental performance
    mean_no3_per_treated_ha =
      mean(no3_per_treated_ha, na.rm = TRUE),

    mean_sed_per_treated_ha =
      mean(sed_per_treated_ha, na.rm = TRUE),

    mean_ghg_per_treated_ha =
      mean(ghg_per_treated_ha, na.rm = TRUE),

    # Biomass performance
    mean_bio_per_treated_ha =
      mean(bio_per_treated_ha, na.rm = TRUE),

    # Treatment composition
    mean_prairie_share_treated =
      mean(prairie_share_treated, na.rm = TRUE),

    mean_rye_share_treated =
      mean(rye_share_treated, na.rm = TRUE),

    # Investment intensity
    mean_dccp_per_treated_ha =
      mean(dccp_per_treated_ha, na.rm = TRUE),
    mean_tccp_per_treated_ha =
      mean(tccp_per_treated_ha, na.rm = TRUE),
    
    #structural feasibility
    mean_stabLow_ha =
      mean(stabLow_ha, na.rm = TRUE),
    
    mean_unprofit_ha =
      mean(unprofit_ha, na.rm = TRUE),
    

    .groups = "drop"
  )

print(performance_summary)

# ------------------------------------------------------------
# 10. Treatment-performance distributions
# ------------------------------------------------------------
facet2_labels <- c(
  bio_per_treated_ha   = "atop(Biomass~Yield,(Mg~ha^{-1}))",
  no3_per_treated_ha      = "atop(NO[3]~Load~Red.,(Mg~ha^{-1}))",
  dccp_per_treated_ha     = "atop(Direct~Cost,(USD~ha^{-1}))",
  oc_per_treated_ha = "atop(Opportunity~Cost,(USD~ha^{-1}))",
  unprofit_ha = "Unprofitable~Area~(%)",
  sed_per_treated_ha      = "atop(Sed.~Load~Red.,(Mg~ha^{-1}))",
  ghg_per_treated_ha      = "atop(GHG~Red.,(Mg~CO[2]*e~ha^{-1}))",
  per_treated = "Treated~('%')",
  prairie_share_treated   = "Prairie~('%')",
  rye_share_treated     = "Cereal~Rye~('%')"
)
huc12_perf %>%
  pivot_longer(
    cols = c(
      no3_per_treated_ha,
      sed_per_treated_ha,
      ghg_per_treated_ha,
      bio_per_treated_ha,
      dccp_per_treated_ha,
      rye_share_treated,
      prairie_share_treated,
      oc_per_treated_ha,
      unprofit_ha
      #stabLow_ha,
    ),
    names_to = "Metric",
    values_to = "Value"
  ) %>%
  ggplot(
    aes(
      x = Planning_Class,
      y = Value,
      fill = Planning_Class
    )
  ) +
  geom_boxplot() +
  facet_wrap(~ factor(Metric, c("no3_per_treated_ha","sed_per_treated_ha","ghg_per_treated_ha","bio_per_treated_ha","per_treated","rye_share_treated","prairie_share_treated","dccp_per_treated_ha","oc_per_treated_ha","unprofit_ha")), scales = "free_y",ncol = 2,,
             strip.position = "left",
             labeller = as_labeller(facet2_labels, label_parsed)) +
  ylab(NULL) +
  theme_minimal() +
  theme(text = element_text(family = "serif", size = 9),
    axis.text.x = element_blank(),
    strip.background = element_blank(),
    strip.placement = "outside"
  ) +
  scale_fill_manual(values = c('#377EB8','#4DAF4A','#984EA3','#FF7F00','#FFFF33'), labels = c("Nutrient-Biomass Integration", "Limited Environmental Intervention","Moderate Multifunctional Outcomes","Water-Quality-Biomass Integration","Prairie-Habitat-Nutrient Integration"))

# ------------------------------------------------------------
# 11. Treatment extent versus landscape-scale NO3 outcome
# ------------------------------------------------------------

ggplot(
  huc12_perf,
  aes(
    x = per_treated,
    y = no3_ha,
    color = Planning_Class
  )
) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(
    x = "Proportion of HUC12 Area within Supplyshed Treated",
    y = "N Reduction (kg/ha of HUC12 within Supplyshed)",
    color = "Planning Class"
  ) +
  geom_text_repel(
    aes(label = HUC12),
    size = 3,
    max.overlaps = 10
  ) +
  scale_fill_manual(values = c('#377EB8','#4DAF4A','#984EA3','#FF7F00','#FFFF33'))

# ------------------------------------------------------------
# 12. Treatment extent versus treatment-level NO3 performance
# ------------------------------------------------------------

ggplot(
  huc12_perf,
  aes(
    x = per_treated,
    y = no3_per_treated_ha,
    color = Planning_Class
  )
) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(
    x = "Proportion of HUC12 Area within Supplyshed Treated",
    y = "N Reduction (kg/treated ha)",
    color = "Planning Class"
  ) +
  geom_text_repel(
    aes(label = HUC12),
    size = 3,
    max.overlaps = 10
  ) +
  scale_fill_manual(values = c('#377EB8','#4DAF4A','#984EA3','#FF7F00','#FFFF33'))

write.csv(
  huc12_perf,
  "../data/tidy/huc12_treatment_performance.csv",
  row.names = FALSE
)

write.csv(
  performance_summary,
  "../data/tidy/treatment_performance.csv",
  row.names = FALSE
)
performance_summary
```


```{r structural_economic, dependson="planning_clusters"}

# ============================================================
# STRUCTURAL AND ECONOMIC CONTEXT
# ============================================================
#
# These variables are intentionally evaluated after the
# environmental/implementation classification. They are not
# used to define the planning classes.
# ============================================================

huc12_context <- huc12_planning %>%
  mutate(
    unstable_share_treated =
      if_else(sumOPha > 0, sum_UNSTha / area_ha, NA_real_),

    unprofitable_share_treated =
      if_else(sumOPha > 0, sum_UNPha / area_ha, NA_real_),

    opportunity_cost_per_prairie_ha =
      if_else(sumprairie > 0, sumOC / sumprairie, NA_real_)
  )

context_summary <- huc12_context %>%
  group_by(Planning_Class) %>%
  summarise(
    n = n(),

    mean_unstable_share_treated =
      mean(unstable_share_treated, na.rm = TRUE),

    median_unstable_share_treated =
      median(unstable_share_treated, na.rm = TRUE),

    mean_unprofitable_share_treated =
      mean(unprofitable_share_treated, na.rm = TRUE),

    median_unprofitable_share_treated =
      median(unprofitable_share_treated, na.rm = TRUE),

    mean_opportunity_cost_per_prairie_ha =
      mean(opportunity_cost_per_prairie_ha, na.rm = TRUE),

    median_opportunity_cost_per_prairie_ha =
      median(opportunity_cost_per_prairie_ha, na.rm = TRUE),

    .groups = "drop"
  )

print(context_summary)

write.csv(
  huc12_context,
  "../data/tidy/huc12_planning_context.csv",
  row.names = FALSE
)

```