---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())

library("factoextra")
library("cluster")
library("ggrepel")
library("fmsb")
library("stringr")


options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```


Look at bioyield and transportation costs
```{r mean_data, dependson = "create_soilpad"}
wsArea <- read_csv("../data/raw/HUC12_list.csv") %>%
  mutate(area_ha = areaacres *0.404686,
         HUC12 = str_pad(huc12, width = 12, pad = "0")) %>%
  select(area_ha, HUC12)


## How much is it going to cost to realize the INRS? How much to achieve wildlife goals?
envOutcome_CostSum <- practSumBIO %>%
  #group_by(practice) %>%
  group_by(FBndID) %>%
  #group_by(radial,biomass) %>%
  summarize(n       = n(),
            MLRA = max(MLRA),
            HUC12 = max(HUC12),
            radial = max(radial),
            IWAP = list(unique(IWAP)),
            practice = list(unique(practice)),
            
            ## Cost summary per field
            opArea_ha = sum(opArea_ha),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            sumDCcp = sum(DirectCost_CP),
            sumTCcp = sum(TotalCost_CP),
            
            ## Bio yield summary
            sum_BioMg = sum(bioYield_Mg),
            DC_BioMg = sum_BioMg / sumDC,
            DCcp_BioMg = sum_BioMg / sumDCcp,
            TC_BioMg = sum_BioMg / sumTC,
            TCcp_BioMg = sum_BioMg / sumTCcp,
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #BioTC_Mg_med = median(TC_MgBio, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #BioTCcp_Mg_med = median(TCcp_MgBio, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## Energy potential summary
            sumEnergyPot = sum(energyPot),
            DC_MMBtu = sumDC / sumEnergyPot,
            DCcp_MMBtu = sumDCcp / sumEnergyPot,
            TC_MMBtu = sumTC / sumEnergyPot,
            TCcp_MMBtu = sumTCcp / sumEnergyPot,
            #engPot_med = median(energyPot, na.rm = TRUE),
            #Q1_engPot = quantile(energyPot, probs = c(0.25)),
            #Q3_engPot = quantile(energyPot, probs = c(0.75)),
            #engPotTC_med = median(TC_enPot, na.rm = TRUE),
            #Q1TC_enPot = quantile(TC_enPot, probs = c(0.25)),
            #Q3TC_enPot = quantile(TC_enPot, probs = c(0.75)),
            #engPotTCcp_med = median(TCcp_enPot, na.rm = TRUE),
            #Q1TCcp_enPot = quantile(TCcp_enPot, probs = c(0.25)),
            #Q3TCcp_enPot = quantile(TCcp_enPot, probs = c(0.75)),
            
            ## Wildlife Summary
            sum_patch_ha = sum(patch_ha),
            sum_lin_ha = sum(lin_ha),
            sum_wh_ha = sum(lin_ha) + sum(patch_ha),
            sum_rye_ha = sum(rye_ha),
            DC_pha = sumDC / sum(patch_ha),
            DC_lha = sumDC / sum(lin_ha),
            DC_wha = sumDC / sum(lin_ha) + sum(patch_ha),
            DCcp_pha = sumDCcp / sum(patch_ha),
            DCcp_lha = sumDCcp / sum(lin_ha),
            DCcp_wha = sumDCcp / sum(lin_ha) + sum(patch_ha),
            TC_pha = sumTC / sum(patch_ha),
            TC_lha = sumTC / sum(lin_ha),
            TC_wha = sumTC / sum(lin_ha) + sum(patch_ha),
            TCcp_pha = sumTCcp / sum(patch_ha),
            TCcp_lha = sumTCcp / sum(lin_ha),
            TCcp_wha = sumTCcp / sum(lin_ha) + sum(patch_ha),
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #WHTC_ha_med = median(TC_haWH, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            #WHTCcp_ha_med = median(TCcp_haWH, na.rm = TRUE),
            #Q1TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.25)),
            #Q3TCcp_MgBio = quantile(TCcp_MgBio, probs = c(0.75)),
            
            ## CO2 summary
            sumCO2 = sum(CO2red),
            DC_CO2 = sumDC / sumCO2,
            DCcp_CO2 = sumDCcp / sumCO2,
            TC_CO2 = sumTC / sumCO2,
            TCcp_CO2 = sumTCcp / sumCO2,
            #CO2red_med = median(CO2red, na.rm = TRUE),
            #Q1_CO2red = quantile(CO2red, probs = c(0.25)),
            #Q3_CO2red = quantile(CO2red, probs = c(0.75)),
            #CO2TC_Mg_med = median(TC_MgCO2, na.rm=TRUE),
            #Q1_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.25)),
            #Q3_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.75)),
            #CO2TCcp_Mg_med = median(TCcp_MgCO2, na.rm=TRUE),
            #Q1_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.25)),
            #Q3_CO2TCcp_Mg = quantile(TCcp_MgCO2, probs = c(0.75)),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),
            DC_N2Ored = sumDC / sumN2Ored,
            DCcp_N2Ored = sumDCcp / sumN2Ored,
            TC_N2Ored = sumTC / sumN2Ored,
            TCcp_N2Ored = sumTCcp / sumN2Ored,
            #N2Ored_med = median(N2Ored, na.rm=TRUE),
            #Q1_N2Ored = quantile(N2Ored, probs = c(0.25)),
            #Q3_N2Ored = quantile(N2Ored, probs = c(0.75)),
            #N2OTC_Mg_med = median(TC_MgN2O, na.rm=TRUE),
            #Q1_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.25)),
            #Q3_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.75)),
            #N2OTCcp_Mg_med = median(TCcp_MgN2O, na.rm=TRUE),
            #Q1_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.25)),
            #Q3_N2OTCcp_Mg = quantile(TCcp_MgN2O, probs = c(0.75)),
            
            # NO3 load summary
            sumNO3red = sum(cpNO3ldRedkg, na.rm = TRUE),
            DC_NO3red = sumDC / sumNO3red,
            DCcp_NO3red = sumDCcp / sumNO3red,
            TC_NO3red = sumTC / sumNO3red,
            TCcp_NO3red = sumTCcp / sumNO3red,
            #NO3red_med = median(cpNO3ldRedkg, na.rm = TRUE),
            #Q1_NO3red = quantile(cpNO3ldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3red = quantile(cpNO3ldRedkg, probs = c(0.75), na.rm = TRUE),
            #NO3TC_kg_med = median(TC_kgNO3, na.rm = TRUE),
            #Q1_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.75), na.rm = TRUE),
            #NO3TCcp_kg_med = median(TCcp_kgNO3, na.rm = TRUE),
            #Q1_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TCcp_kg = quantile(TCcp_kgNO3, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            sumSEDred = sum(cpSEDldRedkg, na.rm = TRUE),
            DC_SEDred = sumDC / sumSEDred,
            DCcp_SEDred = sumDCcp / sumSEDred,
            TC_SEDred = sumTC / sumSEDred,
            TCcp_SEDred = sumTCcp / sumSEDred,
            #SEDred_med = median(cpSEDldRedkg, na.rm = TRUE),
            #Q1_SEDred = quantile(cpSEDldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDred = quantile(cpSEDldRedkg, probs = c(0.75), na.rm = TRUE),
            #SEDTC_kg_med = median(TC_kgSED, na.rm = TRUE),
            #Q1_SEDTC_kg = quantile(TC_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTC_kg = quantile(TC_kgSED, probs = c(0.75), na.rm = TRUE),
            #SEDTCcp_kg_med = median(TCcp_kgSED, na.rm = TRUE),
            #Q1_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTCcp_kg = quantile(TCcp_kgSED, probs = c(0.75), na.rm = TRUE),
            )

write_csv(envOutcome_CostSum,"envOutcome_byField.csv")

travel_envOutcomes <- full_join(envOutcome_CostSum, fbSieversRoute)
profit_trvl_env <- full_join(AvgProfit, travel_envOutcomes) %>%
  drop_na(n)

travel_HUC12Sum <- travel_envOutcomes %>%
  #group_by(radial) %>%
  group_by(FBndID,HUC12) %>%
  drop_na(Total_Kilometers) %>%
  summarize(AOI = "supplyshed",
            opArea = sum(opArea_ha),
            n       = n(),
            ## Bio yield summary
            BioMg = sum(sum_BioMg),
            
            ## Energy potential summary
            EnergyPot = sum(sumEnergyPot),

            ## Cost summary per field
            DC = sum(sumDC),
            OC = sum(sumOC),
            TC = sum(sumTC),
            DCcp = sum(sumDCcp),
            TCcp = sum(sumTCcp),
            
            ## Wildlife habitat summary
            patch = sum(sum_patch_ha),
            lin = sum(sum_lin_ha),
            prairie = sum(sum_wh_ha),
            rye = sum(sum_rye_ha),

            ## CO2 summary
            CO2 = sum(sumCO2),
            
            ## N2O summary
            N2Ored = sum(sumN2Ored),

            # NO3 load summary
            NO3red = sum(sumNO3red, na.rm = TRUE),

            ## Sediment load summary
            SEDred = sum(sumSEDred, na.rm = TRUE),
            
            Ctruck = sum_BioMg*(2*Total_Kilometers)*0.265, # $ per field. trucking cost. 2026 ISU Custom Rate survey. Transportation coefficient = "haul round bales by truck or trailer per bale per mile", assuming 0.68 Mg of hay in a bale (Hart etal. 2015).
            Ctruck_Mg = (2*Total_Kilometers)*0.265,
            Chand = sum_BioMg*4.7794, # $ per field. 2026 ISU Custom Rate survey. Loading/unloading = "moving large round bales to storage per bale", assuming 0.68 Mg of hay in a bale. Coefficients are assumed to be fixed cost. 
            Ctotal = Ctruck + Chand, # trucking + handling costs per field.
            rnd_dist = 2*Total_Kilometers,
            Ctotal_Mg = (Ctruck + Chand) / sum_BioMg, # transportation cost per Mg of biomass harvested from a field
            Ctotal_Mg_km = Ctotal / sum_BioMg / rnd_dist,
            Cdeliv = Ctotal + sumDC, # cost per field for biomass
            Cdeliv_Mg = Cdeliv / sum_BioMg, # production + transportation cost per Mg delivered from a field
            Cdeliv_Mg_km = Cdeliv / sum_BioMg / rnd_dist,
            Ccpdeliv = Ctotal + sumDCcp, # cost per field for biomass and structural components
            Ccpdeliv_Mg = Ccpdeliv / sum_BioMg,
            Ccpdeliv_Mg_km = Ccpdeliv / sum_BioMg / rnd_dist
            )

profitHUC12 <- profit_yield %>%
  filter(unprofit == "unprofitable") %>%
  group_by(HUC12) %>%
  summarize(sum_UNPha = sum(subArea_ha)) %>%
  drop_na()

ysHUC12 <- profit_yield %>%
  filter(stabCorn == "Unstable") %>%
  group_by(HUC12) %>%
  summarize(sum_UNSTha = sum(subArea_ha)) #%>%
  #drop_na()
  
Ctravel_HUC12 <- travel_HUC12Sum %>%
  #group_by(radial) %>%
  group_by(HUC12) %>%
  summarize(sumOPha = sum(opArea),
            sumBioMg = sum(BioMg),
            
            ## Energy potential summary
            sumEnergyPot = sum(EnergyPot),
            sumDC = sum(DC),
            sumOC = sum(OC),
            sumTC = sum(TC),
            sumDCcp = sum(DCcp),
            sumTCcp = sum(TCcp),
            
            ## Wildlife habitat summary
            sumpatch = sum(patch),
            sumlin = sum(lin),
            sumprairie = sum(prairie),
            sumrye = sum(rye),
            
            ## CO2 summary
            sumCO2 = sum(CO2),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),

            # NO3 load summary
            sumNO3red = sum(NO3red, na.rm = TRUE)*0.001,
            
            ## Sediment load summary
            sumSEDred = sum(SEDred, na.rm = TRUE)*0.001,
            
            mean_dist = mean(rnd_dist, na.rm = TRUE),
            #sd_dist = sd(rnd_dist),
            #med_dist = median(rnd_dist, na.rm = TRUE),
            #Q1_dist = quantile(rnd_dist, probs = c(0.25), na.rm = TRUE),
            #Q3_dist = quantile(rnd_dist, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctruck = mean(Ctruck, na.rm = TRUE),
            sum_Ctruck = sum(Ctruck),
            mean_Ctruck = mean(Ctruck_Mg, na.rm=TRUE),
            #sd_Ctruck = sd(Ctruck),
            #med_Ctruck = median(Ctruck_Mg, na.rm = TRUE),
            #Q1_Ctruck = quantile(Ctruck_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctruck = quantile(Ctruck_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Chand = mean(Chand, na.rm = TRUE),
            sum_Chand = sum(Chand, na.rm = TRUE),
            #sd_Chand = sd(Chand),
            #med_Chand = median(Chand, na.rm = TRUE),
            #Q1_Chand = quantile(Chand, probs = c(0.25), na.rm = TRUE),
            #Q3_Chand = quantile(Chand, probs = c(0.75), na.rm = TRUE),
            
            mean_Ctotal = mean(Ctotal, na.rm = TRUE),
            sum_Ctotal = sum(Ctotal, na.rm = TRUE),
            #sd_Ctotal = sd(Ctotal, na.rm = TRUE),
            #med_Ctotal = median(Ctotal, na.rm = TRUE),
            #Q1_Ctotal = quantile(Ctotal, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctotal = quantile(Ctotal, probs = c(0.75), na.rm = TRUE),
           
            mean_Ctotal_Mg = mean(Ctotal_Mg, na.rm = TRUE),
            #sd_Ctotal_Mg = sd(Ctotal_Mg),
            #med_Ctotal_Mg = median(Ctotal_Mg, na.rm = TRUE),
            #Q1_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Ctotal_Mg = quantile(Ctotal_Mg, probs = c(0.75), na.rm = TRUE),
            
            mean_Cdeliv = mean(Cdeliv, na.rm = TRUE),
            sum_Cdeliv = sum(Cdeliv, na.rm = TRUE),
            #sd_Cdeliv = sd(Cdeliv),
            #med_Cdeliv = median(Cdeliv, na.rm = TRUE),
            #Q1_Cdeliv = quantile(Cdeliv, probs = c(0.25), na.rm = TRUE),
            #Q3_Cdeliv = quantile(Cdeliv, probs = c(0.75), na.rm = TRUE),
            mean_Cdeliv_Mg = mean(Cdeliv_Mg, na.rm = TRUE),
            #sd_Cdeliv_Mg =sd(Cdeliv_Mg),
            #med_Cdeliv_Mg = median(Cdeliv_Mg, na.rm = TRUE),
            #Q1_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.25), na.rm = TRUE),
            #Q3_Cdeliv_Mg = quantile(Cdeliv_Mg, probs = c(0.75), na.rm = TRUE)
  )

write_csv(Ctravel_radial,"travelcosts_byRad.csv")

huc12_summary <- full_join(Ctravel_HUC12, wsArea)

huc12_summary <- wsArea %>%
  full_join(Ctravel_HUC12) %>%
  full_join(ysHUC12) %>%
  full_join(profitHUC12) %>%
  drop_na(HUC12,sumOPha) %>%
  replace_na(list(sum_UNSTha = 0)) ## 7 HUC12 watersheds had 0 subfields designated as unstable


huc12_df <- huc12_summary %>%
  #drop_na() %>%
  mutate(per_treated = (sumOPha / area_ha)*100,
         #per_unstable = sum_UNSTha / area_ha,
         #per_unprofit = sum_UNPha / area_ha,
         per_patch = sumpatch / area_ha,
         per_lin = sumlin / area_ha,
         per_prairie = sumprairie / area_ha,
         per_rye = sumrye / area_ha,
         bio_Mg_ha = sumBioMg/area_ha,
         #dc_ha = sumDC / area_ha,
         #oc_ha = sumOC / area_ha,
         #tc_ha = sumTC / area_ha,
         dccp_ha = sumDCcp / area_ha,
         #tccp_ha = sumTCcp / area_ha,
         co2_ha = sumCO2 / area_ha,
         n20_ha = sumN2Ored /area_ha,
         no3_ha = sumNO3red / area_ha,
         sed_ha = sumSEDred / area_ha
         #NO3_TC = sumNO3red / sumTC,
         #NO3_TCcp = sumNO3red / sumTCcp,
         #SED_TC = sumSEDred / sumTC,
         #SED_TCcp = sumSEDred / sumTCcp,
         #BIO_TC = sumBioMg / sumTC,
         #BIO_TCcp = sumBioMg / sumTCcp,
         #area_TC = sumOPha / sumTC,
         #area_TCcp = sumOPha / sumTCcp
         )
         

envOutcome_CostSum %>%
  group_by(FBndID) %>%
  filter(sum_wh_ha > 49 ) %>% ## summarize core habitat great than 50. need a citation. summarize linear less than 50 ha. do this for all prairie practices. 
  summarize(n = n(),
            mean_ha = mean(sum_wh_ha),
            med_ha = median(sum_wh_ha),
            Q1_ha = quantile(sum_wh_ha, probs = c(0.25), na.rm = TRUE),
            Q3_ha = quantile(sum_wh_ha, probs = c(0.75), na.rm = TRUE),
            min_ha = min(sum_wh_ha),
            max_ha = max(sum_wh_ha),
            sum_ha = sum(sum_wh_ha))

envOutcome_CostSum %>%
  filter(sum_wh_ha < 50) %>%
  summarize(n = n(),
            mean_ha = mean(sum_wh_ha),
            med_ha = median(sum_wh_ha),
            Q1_ha = quantile(sum_wh_ha, probs = c(0.25), na.rm = TRUE),
            Q3_ha = quantile(sum_wh_ha, probs = c(0.75), na.rm = TRUE),
            min_ha = min(sum_wh_ha),
            max_ha = max(opArea_ha),
            sum_ha = sum(sum_wh_ha))

```

```{r mean_data, dependson = "create_soilpad"}
huc12_ext <- huc12_df

vars <- huc12_ext %>%
  select(co2_ha,n20_ha,no3_ha,sed_ha,per_patch,per_lin,per_rye,bio_Mg_ha,dccp_ha)

vars_scaled <- scale(vars)

fviz_nbclust(vars_scaled, kmeans, method = "wss")
fviz_nbclust(vars_scaled, kmeans, method = "silhouette")
```

```{r mean_data, dependson = "create_soilpad"}
set.seed(123)

k <- 3

km_model <- kmeans(vars_scaled, centers = k, nstart = 25)

huc12_ext$cluster <- as.factor(km_model$cluster)

cluster_summary <- huc12_ext %>%
  group_by(cluster) %>%
  summarize(across(c(co2_ha,n20_ha,no3_ha,sed_ha,per_patch,per_lin,per_rye,bio_Mg_ha,dccp_ha), mean, na.rm = TRUE))

print(cluster_summary)
```

```{r mean_data, dependson = "create_soilpad"}
huc12_ext <- huc12_ext %>%
  mutate(Cluster_Label = case_when(
    cluster == "1" ~ "THE/MC", 
    cluster == "2" ~ "LO/LC", 
    cluster == "3" ~ "HO/HC" 
  ))

```

```{r mean_data, dependson = "create_soilpad"}
ggplot(huc12_ext, aes(x = (per_treated),
                     y = no3_ha,
                     color = Cluster_Label)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(x = "Percent Treated",
       y = "N Reduction (kg/ha)",
       color = "Cluster") +
  geom_text_repel(aes(label = HUC12),
                  size = 3,
                  max.overlaps = 10)

```


```{r mean_data, dependson = "create_soilpad"}
fviz_cluster(km_model,
             data = vars_scaled,
             geom = "point",
             ellipse.type = "convex",
             ggtheme = theme_minimal())

```


```{r mean_data, dependson = "create_soilpad"}
huc12_ext %>%
  pivot_longer(c(no3_ha,sed_ha,co2_ha,n20_ha,per_patch,per_lin,per_rye,bio_Mg_ha,dccp_ha),
               names_to = "Metric",
               values_to = "Value") %>%
  ggplot(aes(x = cluster,
             y = Value,
             fill = cluster)) +
  geom_boxplot() +
  theme_minimal() +
  theme(axis.text.x = element_text(hjust = 1)) +
  facet_wrap(~factor(Metric, levels = c("no3_ha","sed_ha","co2_ha","n20_ha","per_patch","per_lin","per_rye","bio_Mg_ha","dccp_ha")), scales = "free_y", ncol=3) +
  scale_fill_manual(values = c('#7CE29F','#5F999C','#9C9B5C'))

```

```{r mean_data, dependson = "create_soilpad"}
write.csv(huc12_ext, "../data/tidy/huc12ext_clustersv2.csv", row.names = FALSE)

anova_result <- aov(co2_ha ~ cluster, data = huc12_df)
summary(anova_result)

```

## Create efficiency-based scenarios (above is extent)
```{r mean_data, dependson = "create_soilpad"}
huc12_eff <- huc12_df

huc12_eff <- huc12_eff %>%
  mutate(
    no3_eff = no3_ha / per_treated,
    sed_eff = sed_ha / per_treated,
    co2_eff = co2_ha / per_treated,
    n2o_eff = n20_ha / per_treated,
    patch_eff = sumpatch / per_treated,
    lin_eff = sumlin / per_treated,
    prairie_eff = patch_eff + lin_eff,
    rye_eff = sumrye / per_treated,
    bio_eff = bio_Mg_ha / per_treated,
    dccp_eff = dccp_ha / per_treated # cost per treated area
  ) %>%
  drop_na()

vars_eff <- huc12_eff %>%
  select(no3_eff,sed_eff,co2_eff,n2o_eff,prairie_eff,rye_eff,bio_eff,dccp_eff) %>%
  drop_na()

vars_eff_scaled <- scale(vars_eff)

```

```{r mean_data, dependson = "create_soilpad"}
fviz_nbclust(vars_eff_scaled, kmeans, method = "wss")
fviz_nbclust(vars_eff_scaled, kmeans, method = "silhouette")

```

```{r mean_data, dependson = "create_soilpad"}
km_eff <- kmeans(vars_eff_scaled, centers = 2, nstart = 25)

huc12_eff$Cluster <- as.factor(km_eff$cluster)

huc12_eff_summary <- huc12_eff %>%
  group_by(Cluster) %>%
  summarise(across(c(no3_eff,sed_eff,co2_eff,n2o_eff,prairie_eff,rye_eff,bio_eff,dccp_eff),
                   mean, na.rm = TRUE))

print(huc12_eff_summary)
```

```{r mean_data, dependson = "create_soilpad"}
huc12_eff <- huc12_eff %>%
  mutate(Cluster_Label = case_when(
    Cluster == "1" ~ "Balanaced / LC", # low opportunity, low cost
    Cluster == "2" ~ "WQ / MC", # extensive transformation, high cost
    Cluster == "3" ~ "HO / HC" # targeted high efficiency, medium cost
  ))

head(huc12_eff)
```

```{r mean_data, dependson = "create_soilpad"}
ggplot(huc12_eff, aes(x = dccp_eff,
                     y = no3_eff,
                     color = Cluster_Label)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(x = "Total Biomass Cost ($2026)",
       y = "N Reduction Efficiency (kg/ha)",
       color = "Cluster") +
  geom_text_repel(aes(label = HUC12),
                  size = 3,
                  max.overlaps = 10)

```


```{r mean_data, dependson = "create_soilpad"}
fviz_cluster(km_eff,
             data = vars_eff_scaled,
             geom = "point",
             ellipse.type = "convex",
             ggtheme = theme_minimal())

```


```{r mean_data, dependson = "create_soilpad"}
huc12_eff %>%
  pivot_longer(cols = c(no3_eff,sed_eff,co2_eff,n2o_eff,prairie_eff,rye_eff,bio_eff,dccp_eff),
               names_to = "Metric",
               values_to = "Value") %>%
  ggplot(aes(x = Cluster,
             y = Value,
             fill = Cluster)) +
  geom_boxplot() +
  facet_wrap(~factor(Metric, levels = c("no3_eff","sed_eff","prairie_eff","co2_eff","n2o_eff","rye_eff","bio_eff","dccp_eff")), scales = "free_y", ncol=3) +
  theme_minimal() +
  theme(axis.text.x = element_text(hjust = 1)) +
  scale_fill_manual(values = c('#C6A741','#F2E3BF','#F9ED35'))
  #scale_fill_manual(values = c('#C6A741','#F2E3BF'))

write.csv(huc12_eff, "../data/tidy/huc12eff_clustersv2.csv", row.names = FALSE)

```



```{r mean_data, dependson = "create_soilpad"}
huc12ext_struc <- huc12_ext %>%
  group_by(cluster) %>%
  summarize(n = n(),
            mean_UNSTB = mean(sum_UNSTha/sumOPha),
            med_UNSTB = median(sum_UNSTha/sumOPha),
            Q1_UNSTB = quantile((sum_UNSTha/sumOPha), probs = c(0.25), na.rm = TRUE),
            Q3_UNSTB = quantile((sum_UNSTha/sumOPha), probs = c(0.75), na.rm = TRUE),
            per_UNST = sum(sum_UNSTha)/ sum(sumOPha),
            mean_UNP = mean(sum_UNPha/sumOPha),
            med_UNP = median(sum_UNPha/sumOPha),
            Q1_UNP = quantile((sum_UNPha/sumOPha), probs = c(0.25), na.rm = TRUE),
            Q3_UNP = quantile((sum_UNPha/sumOPha), probs = c(0.75), na.rm = TRUE),
            per_UNP = sum(sum_UNPha) / sum(sumOPha),
            mean_OC = mean(sumOC / sumprairie)
            )

huc12eff_unp <- huc12_eff %>%
  group_by(Cluster) %>%
  summarize(n = n(),
            mean_UNP = mean(sum_UNPha/sumOPha),
            med_UNP = median(sum_UNPha/sumOPha),
            Q1_UNP = quantile((sum_UNPha/sumOPha), probs = c(0.25), na.rm = TRUE),
            Q3_UNP = quantile((sum_UNPha/sumOPha), probs = c(0.75), na.rm = TRUE),
            per_UNP = sum(sum_UNPha) / sum(sumOPha),
            mean_OC = mean(sumOC / sumprairie)
            ) 

huc12eff_unst <- huc12_eff %>%
  group_by(Cluster) %>%
  filter(sum_UNSTha >0) %>%
  summarize(nst = n(),
            mean_UNSTB = mean(sum_UNSTha/sumOPha),
            med_UNSTB = median(sum_UNSTha/sumOPha),
            Q1_UNSTB = quantile((sum_UNSTha/sumOPha), probs = c(0.25), na.rm = TRUE),
            Q3_UNSTB = quantile((sum_UNSTha/sumOPha), probs = c(0.75), na.rm = TRUE),
            per_UNST = sum(sum_UNSTha)/ sum(sumOPha))


```

