---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())

options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```


```{r create_df, cache.extra=tools::md5sum("../code/CBS_practiceSummary.csv")}
## Generate dataframe
## crop acres = all cropped acres within the drainage area of the practice.
CBS_BIOraw <- read_csv("../data/raw/CBS_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "CBS",
         pID = FBndID,
         IWAP = 2,
         INRS = "Perennial crops",
         biomass = "prairie",
         adjOCost = OpportunityCost,
         DirectCost_CP = DirectCost,
         TotalCost_CP = DirectCost_CP + OpportunityCost,
         opArea_ha = opAcres*0.404686, ## convert ac to ha
         patch_ha = 0,
         lin_ha = opArea_ha,
         rye_ha = 0,
         cropArea_ha = SUM_cropAcres*0.404686, ## convert ac to ha
         DC_haWH = DirectCost/opArea_ha,
         DCcp_haWH = DirectCost_CP/opArea_ha,
         TC_haWH = TotalCost/opArea_ha,
         TCcp_haWH = TotalCost_CP/opArea_ha,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)

## crop acres = all cropped acres within the drainage area of the practice.
NRW_BIOraw <- read_csv("../data/raw/NRW_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "NRW",
         pID = SiteID,
         IWAP = 0,
         INRS = "Treatment wetlands",
         biomass = "prairie",
         adjOCost = OpportunityCost,
         TotalCost_CP = DirectCost_CP + OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         patch_ha = 0,
         lin_ha = 0,
         rye_ha = 0,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = SUM_cropAcres*0.404686, # convert ac to ha
         DC_haWH = DirectCost/opArea_ha,
         DCcp_haWH = DirectCost_CP/opArea_ha,
         TC_haWH = TotalCost/opArea_ha,
         TCcp_haWH = TotalCost_CP/opArea_ha,
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)

## crop acres = field acres
PCP_BIOraw <- read_csv("../data/raw/PCP_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "PCP",
         pID = FBndID,
         IWAP = 1,
         INRS = "Perennial crops",
         biomass = "prairie",
         DirectCost_CP = DirectCost,
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         patch_ha = opArea_ha,
         lin_ha = 0,
         rye_ha = 0,
         TotalCost_CP = DirectCost_CP + OpportunityCost,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = cropAcres*0.404686, # convert ac to ha
         DC_haWH = DirectCost/opArea_ha,
         DCcp_haWH = DirectCost_CP/opArea_ha,
         TC_haWH = TotalCost/opArea_ha,
         TCcp_haWH = TotalCost_CP/opArea_ha,
         cpNO3ldkg = cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)

## crop acres = all cropped acres within the drainage area of the practice.
STB_BIOraw <- read_csv("../data/raw/STB_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "STB",
         pID = riparianid,
         IWAP = 2,
         INRS = "Riparian buffers",
         biomass = "prairie",
         adjOCost = adjOCosts,
         TotalCost = adjOCost + DirectCost,
         TotalCost_CP = DirectCost_CP + adjOCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         patch_ha = 0,
         lin_ha = opArea_ha,
         rye_ha = 0,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = SUM_cropAcres*0.404686, # convert ac to ha
         DC_haWH = DirectCost/opArea_ha,
         DCcp_haWH = DirectCost_CP/opArea_ha,
         TC_haWH = TotalCost/opArea_ha,
         TCcp_haWH = TotalCost_CP/opArea_ha,
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)

RIB_BIOraw <- read_csv("../data/raw/RIB_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "RIB",
         pID = riparianid,
         IWAP = 2,
         INRS = "Riparian buffers",
         biomass = "prairie",
         adjOCost = adjOCosts,
         TotalCost = adjOCost + DirectCost,
         TotalCost_CP = DirectCost_CP + adjOCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         patch_ha = 0,
         lin_ha = opArea_ha,
         rye_ha = 0,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = SUM_cropAcres*0.404686, # convert ac to ha
         DC_haWH = DirectCost/opArea_ha,
         DCcp_haWH = DirectCost_CP/opArea_ha,
         TC_haWH = TotalCost/opArea_ha,
         TCcp_haWH = TotalCost_CP/opArea_ha,
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)


## crop acres = field acres
WCR_BIOraw <- read_csv("../data/raw/WCR_practiceSummary_BIOv4.csv") %>%
  mutate(practice = "WCR",
         pID = FBndID,
         IWAP = 0,
         INRS = "Rye cover crops",
         biomass = "rye",
         DirectCost_CP = DirectCost,
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         patch_ha = 0,
         lin_ha = 0,
         rye_ha = opArea_ha,
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = cropAcres*0.404686, # convert ac to ha
         DC_haWH = 0,
         DCcp_haWH = 0,
         TC_haWH = 0,
         TCcp_haWH = 0,
         TotalCost = DirectCost,
         cpNO3ldkg = cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = cpSEDLoadReduced*907.18, ## convert US tons to kg
         TotalCost_CP = TotalCost,
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         DCcp_kgNO3 = DirectCost_CP / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         TCcp_kgNO3 = TotalCost_CP / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         DCcp_kgSED = DirectCost_CP / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         TCcp_kgSED = TotalCost_CP / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         DCcp_MgCO2 = DirectCost_CP / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         TCcp_MgCO2 = TotalCost_CP / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         DCcp_MgN2O = DirectCost_CP / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         TCcp_MgN2O = TotalCost_CP / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         DCcp_MgBio = DirectCost_CP / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         TCcp_MgBio = TotalCost_CP / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         DCcp_enPot = DirectCost_CP / energyPot,
         TC_enPot = TotalCost / energyPot,
         TCcp_enPot = TotalCost_CP / energyPot) %>%
  select(MLRA,radial,HUC12,FBndID,pID,practice,biomass,opArea_ha,patch_ha,
         lin_ha,rye_ha,cropArea_ha,IWAP,
         INRS,DirectCost,DirectCost_CP,OpportunityCost,adjOCost,TotalCost,
         TotalCost_CP,DC_haWH,DCcp_haWH,TC_haWH,TCcp_haWH,biomass,bioYield_Mg,
         energyPot,CO2red,N2Ored,cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,DCcp_kgNO3,TC_kgNO3,TCcp_kgNO3,DC_kgSED,DCcp_kgSED,TC_kgSED,
         TCcp_kgSED,DC_MgBio,DCcp_MgBio,TC_MgBio,TCcp_MgBio,DC_enPot,DCcp_enPot,
         TC_enPot,TCcp_enPot,DC_MgCO2,DCcp_MgCO2,TC_MgCO2,TCcp_MgCO2,DC_MgN2O,
         DCcp_MgN2O,TC_MgN2O,TCcp_MgN2O)

practSumBIO_df <- rbind(CBS_BIOraw, NRW_BIOraw, PCP_BIOraw, STB_BIOraw, RIB_BIOraw, WCR_BIOraw)
practSumBIO <- within(practSumBIO_df, MLRA[MLRA == 108] <- "108c")
practSumBIO <- within(practSumBIO, MLRA[MLRA == 115] <- "115c")

fbSieversRoute <-  read_csv("../data/raw/fbSieversRoutes_v4.csv") %>%
  mutate(FBndID = trimws(sub("^([^-]+)-.*$", "\\1", Name),which="right"),
         rnd_dist = 2*Total_Kilometers,
         rnd_time_hr = (2*Total_TruckTravelTime)/60,
         #km_hr = Total_Kilometers / (Total_TruckTravelTime/60),
         fuel = 5.165*0.26417, # $ per gallon  --> $ per liter reference USDA AMS Transport Report 4/23/2026
         fuel_eff = 1/(5.5*0.425144), # mpg --> kpL --> Liters per km. This value was taken from Gemini AI and should be fact-checked.
         fuel_cost = rnd_dist*fuel_eff*fuel,
         lbr_cost = rnd_time_hr*118, # 2026 ISU Custom Rate Survey. Haul round bales by truck or trailer/ hour
         trans_cost = fuel_cost+lbr_cost
         ) %>%
  select(FBndID,Total_TruckTravelTime,Total_Kilometers,fuel_cost, lbr_cost, trans_cost)

## Generate dataframes
## crop acres = all cropped acres within the drainage area of the practice.
AvgYield <- read_csv("../data/raw/AvgYield012345678912.csv") %>%
  mutate(area_ha = Acres*0.404686, ## convert ac to ha
         subArea_ha = subfield_Acres*0.404686, ## convert bu per acre to kg per ha
         subfieldID = SubfieldID, ## convert ac to ha
         yrsCorn = Years_Corn,
         avgCorn_buha = AvgYield_Corn*0.405, ## convert bu per acre to kg per ha
         stdCorn_buha = StdYield_Corn*0.405, ## convert bu per acre to kg per ha
         cvCorn_per = Yield_CV_Corn*100,
         stabCorn = case_when(cvCorn_per < 5 ~ "Stable",
                              cvCorn_per < 10 ~ "Stable",
                              cvCorn_per < 30 ~ "Stable Low",
                              cvCorn_per > 30  ~ "Unstable"),
         yieldCornClass = case_when(avgCorn_buha < 81.4 | CountyName == "Cedar" ~ "Low", # Cedar County 2015-2024 average = 201.4 bu per ac
                                    avgCorn_buha > 81.4 | CountyName == "Cedar" ~ "High",
                                    avgCorn_buha < 82.1 | CountyName == "Clint" ~ "Low", # Clinton County 2015-2024 average = 202.7 bu per ac
                                    avgCorn_buha > 82.1 | CountyName == "Clint" ~ "High",
                                    avgCorn_buha < 79.4 | CountyName == "Musca" ~ "Low", # Muscatine County 2015-2024 average = 196.1 bu per ac
                                    avgCorn_buha > 79.4 | CountyName == "Musca" ~ "High",
                                    avgCorn_buha < 82.8 | CountyName == "Scott" ~ "Low", # Scott County 2015-2024 average = 204.4 bu per ac
                                    avgCorn_buha > 82.8 | CountyName == "Scott" ~ "High",
                                    avgCorn_buha < 80 | CountyName == "Jones" ~ "Low", # Jones County 2015-2024 average = 197.5 bu per ac
                                    avgCorn_buha > 80 | CountyName == "Jones" ~ "High"),
         yrsSoy = Years_Soy,
         avgSoy_buha = AvgYield_Soy*0.405, ## convert bu per acre to kg per ha
         stdSoy_buha = StdYield_Soy*0.405, ## convert bu per acre to kg per ha
         cvSoy_per = Yield_CV_Soy*100,
         stabSoy = case_when(cvSoy_per < 5 ~ "Stable High",
                             cvSoy_per < 10 ~ "Stable Low",
                             cvSoy_per <= 50  ~ "Unstable"),
         yieldSoyClass = case_when(avgSoy_buha < 24.6 | CountyName == "Cedar" ~ "Low", # Cedar County 2015-2024 average = 60.8 bu per ac
                                    avgSoy_buha > 24.6 | CountyName == "Cedar" ~ "High",
                                    avgSoy_buha < 24.3 | CountyName == "Clint" ~ "Low", # Clinton County 2015-2024 average = 60 bu per ac
                                    avgSoy_buha > 24.3 | CountyName == "Clint" ~ "High",
                                    avgSoy_buha < 24.2 | CountyName == "Musca" ~ "Low", # Muscatine County 2015-2024 average = 59.7 bu per ac
                                    avgSoy_buha > 24.2 | CountyName == "Musca" ~ "High",
                                    avgSoy_buha < 25.8 | CountyName == "Scott" ~ "Low", # Scott County 2015-2024 average = 63.7 bu per ac
                                    avgSoy_buha > 25.8 | CountyName == "Scott" ~ "High",
                                    avgSoy_buha < 23.3 | CountyName == "Jones" ~ "Low", # Jones County 2015-2024 average = 57.5 bu per ac
                                    avgSoy_buha > 23.3 | CountyName == "Jones" ~ "High"),
         AdjYield2015 = AdjYield2015*0.405,
         AdjYield2016 = AdjYield2016*0.405,
         AdjYield2017 = AdjYield2017*0.405,
         AdjYield2018 = AdjYield2018*0.405,
         AdjYield2019 = AdjYield2019*0.405,
         AdjYield2020 = AdjYield2020*0.405,
         AdjYield2021 = AdjYield2021*0.405,
         AdjYield2022 = AdjYield2022*0.405,
         AdjYield2023 = AdjYield2023*0.405,
         AdjYield2024 = AdjYield2024*0.405) %>%
  select(MLRA,HUC12,CountyName,FBndID,area_ha,subfieldID,subArea_ha,Sub_CSR2,
         TotalYears,NullYears,yrsCorn,avgCorn_buha,stdCorn_buha,cvCorn_per,stabCorn,
         yieldCornClass,yrsSoy,
         yieldSoyClass,avgSoy_buha,stdSoy_buha,cvSoy_per,stabSoy,,maj15,
         AdjYield2015,maj16,AdjYield2016,maj17,AdjYield2017,maj18,
         AdjYield2018,maj19,AdjYield2019,maj20,AdjYield2020,maj21,
         AdjYield2021,maj22,AdjYield2022,maj23,AdjYield2023,maj24,
         AdjYield2024)

HUC12 <- read_csv("../data/raw/HUC12_list.csv") %>%
  mutate(HUC12_ha = areaacres*0.405,
         HUC12 = huc12) %>%
  select(HUC12, HUC12_ha, name)

yield <- merge(AvgYield, HUC12, by="HUC12")

AvgProfit <- read_csv("../data/raw/AvgProfit012345678912.csv") %>%
  mutate(area_ha = Acres*0.404686, ## convert ac to ha
         subArea_ha = subfield_Acres*0.404686, ## convert bu per acre to kg per ha
         subfieldID = SubfieldID,
         yrsCorn = rowSums(.[6:16] == 1, na.rm = TRUE),
         yrsSoy = rowSums(.[6:16] == 5, na.rm = TRUE),
         unprofit = case_when(AvgProfit <= 0 ~ "unprofitable",
                              AvgProfit >= 0 ~ "profitable")) %>%
  select(MLRA,HUC12,CountyName,FBndID,area_ha,subfieldID,subArea_ha,Sub_CSR2,
         yrsCorn,yrsSoy,AvgProfit,UnpYears,unprofit)

HUC12 <- read_csv("../data/raw/HUC12_list.csv") %>%
  mutate(HUC12_ha = areaacres*0.405,
         HUC12 = huc12) %>%
  select(HUC12, HUC12_ha, name)

profit <- merge(AvgProfit, HUC12, by="HUC12")

profit_yield <- full_join(AvgProfit, AvgYield)

```
