---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())
library("lme4")
library("lmerTest")
library("emmeans")
library("ggResidpanel")

options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```


```{r create_df, cache.extra=tools::md5sum("../code/CBS_practiceSummary.csv")}
## Generate dataframe
# profit105 <- read_csv("../code/AvgProfit012345678912.csv") %>%
#   group_by(MLRA) %>%
#   reframe(mlra_ha = sum(subfield_Acres)*0.405)

## crop acres = all cropped acres within the drainage area of the practice.
AvgProfit <- read_csv("../data/raw/AvgProfit012345678912.csv") %>%
  mutate(area_ha = Acres*0.404686, ## convert ac to ha
         subArea_ha = subfield_Acres*0.404686, ## convert bu per acre to kg per ha
         subfieldID = SubfieldID,
         yrsCorn = rowSums(.[6:16] == 1, na.rm = TRUE),
         yrsSoy = rowSums(.[6:16] == 5, na.rm = TRUE),
         unprofit = case_when(AvgProfit <= 0 ~ "unprofitable",
                              AvgProfit >= 0 ~ "profitable")) %>%
  select(MLRA,HUC12,CountyName,FBndID,area_ha,subfieldID,subArea_ha,Sub_CSR2,
         yrsCorn,yrsSoy,AvgProfit,UnpYears,unprofit)

HUC12 <- read_csv("../data/raw/HUC12_list.csv") %>%
  mutate(HUC12_ha = areaacres*0.405,
         HUC12 = huc12) %>%
  select(HUC12, HUC12_ha, name)

profit <- merge(AvgProfit, HUC12, by="HUC12")

```

```{r mean_data, dependson = "create_soilpad"}
profit_MLRA <- profit %>%
  group_by(MLRA,unprofit) %>%
  reframe(subarea_ha = sum(subArea_ha),
         n       = n(),
         avgProfit_ha = mean(AvgProfit*0.405),
         stdProfit = sd(AvgProfit*0.405),
         mlra_ha = case_when(MLRA == "104" ~ 52873,
                               MLRA == "105" ~ 5208,
                               MLRA == "108c" ~ 170354,
                               MLRA == "115c" ~ 1889),
          mlra_wtd = (subarea_ha / mlra_ha)*100) %>%
  distinct()


profit_HUC12 <- profit %>%
  group_by(HUC12,unprofit) %>%
  reframe(subarea_ha = sum(subArea_ha),
         n       = n(),
         avgProfit_ha = mean(AvgProfit*0.405),
         stdProfit = sd(AvgProfit*0.405),
         huc12_wtd = (subarea_ha / HUC12_ha)*100) %>%
  distinct()

unprofit <- profit_HUC12 %>%
  filter(unprofit == "unprofitable") %>%
  arrange(desc(huc12_wtd)) %>%
  slice(1:10)
  

mxProfit = profit_MLRA %>%
  #filter(stabCorn != "Stable High") %>%
  ggplot(aes(x = MLRA, fill = unprofit, y = mlra_wtd)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 90, size = 14, colour = "black", vjust = 0.5, hjust = 1, face= "bold"), 
        axis.title.y = element_text(size = 16, face = "bold"), legend.title = element_text(size = 16, face = "bold"), 
        legend.text = element_text(size = 12, face = "bold", colour = "black"), axis.text.y = 
          element_text(colour = "black", size = 12, face = "bold")) + 
  #scale_y_continuous(expand = c(0,0)) + 
  labs(x = "MLRA", y = "Percent of MLRA (%)", fill = "Profitability") +
  scale_fill_brewer(palette = "Paired")
    
mhProfit <- profit_HUC12 %>% na.omit(avgProfit_ha) %>%
  #filter(huc12_wtd > 5) %>%
  #filter(huc12_wtd > 10) %>%
  ggplot(aes(x = HUC12, fill = unprofit, y = huc12_wtd)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, face= "bold"), axis.title.y = element_text(face = "bold")) +
  labs(x = "HUC12", y = "Percent of MLRA (%)", fill = "Profitability") +
  scale_fill_brewer(palette = "Paired")


mxProfit
mhProfit

```

```{r mean_data, dependson = "create_soilpad"}
profit_yield <- merge(AvgProfit, AvgYield, by="subfieldID")
profit_yield$HUC12 <- profit_yield$HUC12.x
profit_yield2 <- merge(profit_yield, HUC12, by="HUC12")

pyMLRA <- profit_yield %>%
  group_by(MLRA.x,unprofit,stabCorn,yieldCornClass) %>%
  reframe(subarea_ha = sum(subArea_ha.x),
          MLRA = MLRA.x,
          n = n(),
          mlra_ha = case_when(MLRA == "104" ~ 52873,
                               MLRA == "105" ~ 5208,
                               MLRA == "108c" ~ 170354,
                               MLRA == "115c" ~ 1889),
          mlra_wtd = (subarea_ha / mlra_ha)*100,
          combo = paste(stabCorn,yieldCornClass,unprofit, sep = " x ")) %>%
  na.omit() %>%
  distinct()

mxPY <- pyMLRA %>%
  filter(unprofit == "unprofitable") %>%
  ggplot(aes(x = MLRA, fill = combo, y = mlra_wtd)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, face= "bold"), axis.title.y = element_text(face = "bold")) +
  labs(x = "MLRA", y = "Percent of MLRA (%)", fill = "Combo") +
  scale_fill_brewer(palette = "Paired")


pyHUC12 <- profit_yield2 %>%
  group_by(HUC12,unprofit,stabCorn,yieldCornClass) %>%
  reframe(subarea_ha = sum(subArea_ha.x),
          n = n(),
          huc12_wtd = (subarea_ha / HUC12_ha)*100,
          combo = paste(stabCorn,yieldCornClass,unprofit, sep = " x ")) %>%
  na.omit() %>%
  filter(n > 10) %>%
  distinct()

mhPY <- pyHUC12 %>%
  filter(unprofit == "unprofitable") %>%
  ggplot(aes(x = HUC12, fill = combo, y = huc12_wtd)) +
  geom_bar(stat = "identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, face= "bold"), axis.title.y = element_text(face = "bold")) +
  labs(x = "HUC12", y = "Percent of MLRA (%)", fill = "combo") +
  scale_fill_brewer(palette = "Paired")

mhPY
mxPY

unprofit_yield <- pyHUC12 %>%
  filter(unprofit == "unprofitable" & stabCorn == "Unstable") %>%
  arrange(desc(huc12_wtd)) %>%
  slice(1:11) # did the top 11, because the top 10 included a duplicate HUC12
  

```

```{r mean_data, dependson = "create_soilpad"}



```

