---
title: "Supplyshed Scenario Exploration"
author: "J. Stephenson"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE)#,
                      #fig.width = 12,
                      #fig.height = 12)

library("tidyverse"); theme_set(theme_bw())
library("lme4")
library("lmerTest")
library("emmeans")
library("ggResidpanel")

options(scipen = 999, width = 200)

dir.create("fig", showWarnings = FALSE)
```


```{r create_df, cache.extra=tools::md5sum("../code/CBS_practiceSummary.csv")}
## Generate dataframe
## crop acres = all cropped acres within the drainage area of the practice.
CBS_BIOraw <- read_csv("../data/raw/CBS_practiceSummary_BIOv2.csv") %>%
  mutate(practice = "CBS",
         pID = FBndID,
         IWAP = 2,
         INRS = "Perennial crops",
         biomass = "prairie",
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, ## convert ac to ha
         cropArea_ha = SUM_cropAcres*0.404686, ## convert ac to ha
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         TC_enPot = TotalCost / energyPot) %>%
  select(MLRA,HUC12,pID,practice,opArea_ha,cropArea_ha,IWAP,INRS,DirectCost,OpportunityCost,
         adjOCost,TotalCost,FBndID,biomass,bioYield_Mg,energyPot,CO2red,N2Ored,
         cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,TC_kgNO3,DC_kgSED,TC_kgSED,DC_MgBio,TC_MgBio,DC_enPot,TC_enPot,
         DC_MgCO2,TC_MgCO2,DC_MgN2O,TC_MgN2O)

## crop acres = all cropped acres within the drainage area of the practice.
NRW_BIOraw <- read_csv("../data/raw/NRW_practiceSummary_BIOv2.csv") %>%
  mutate(practice = "NRW",
         pID = SiteID,
         IWAP = 0,
         INRS = "Treatment wetlands",
         biomass = "prairie",
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = SUM_cropAcres*0.404686, # convert ac to ha
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         TC_enPot = TotalCost / energyPot) %>%
  select(MLRA,HUC12,pID,practice,opArea_ha,cropArea_ha,IWAP,INRS,DirectCost,OpportunityCost,
         adjOCost,TotalCost,FBndID,biomass,bioYield_Mg,energyPot,CO2red,N2Ored,
         cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,TC_kgNO3,DC_kgSED,TC_kgSED,DC_MgBio,TC_MgBio,DC_enPot,TC_enPot,
         DC_MgCO2,TC_MgCO2,DC_MgN2O,TC_MgN2O)

## crop acres = field acres
PCP_BIOraw <- read_csv("../data/raw/PCP_practiceSummary_BIOv2.csv") %>%
  mutate(practice = "PCP",
         pID = FBndID,
         IWAP = 1,
         INRS = "Perennial crops",
         biomass = "prairie",
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = cropAcres*0.404686, # convert ac to ha
         cpNO3ldkg = cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         TC_enPot = TotalCost / energyPot) %>%
  select(MLRA,HUC12,pID,practice,opArea_ha,cropArea_ha,IWAP,INRS,DirectCost,OpportunityCost,
         adjOCost,TotalCost,FBndID,biomass,bioYield_Mg,energyPot,CO2red,N2Ored,
         cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,TC_kgNO3,DC_kgSED,TC_kgSED,DC_MgBio,TC_MgBio,DC_enPot,TC_enPot,
         DC_MgCO2,TC_MgCO2,DC_MgN2O,TC_MgN2O)

## crop acres = all cropped acres within the drainage area of the practice.
STB_BIOraw <- read_csv("../data/raw/STB_practiceSummary_BIOv2.csv") %>%
  mutate(practice = "STB",
         pID = riparianid,
         IWAP = 2,
         INRS = "Riparian buffers",
         biomass = "prairie",
         adjOCost = adjOCosts,
         TotalCost = adjOCost + DirectCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = SUM_cropAcres*0.404686, # convert ac to ha
         cpNO3ldkg = SUM_cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = SUM_cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = SUM_cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = SUM_cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         TC_enPot = TotalCost / energyPot) %>%
  select(MLRA,HUC12,pID,practice,opArea_ha,cropArea_ha,IWAP,INRS,DirectCost,OpportunityCost,
         adjOCost,TotalCost,FBndID,biomass,bioYield_Mg,energyPot,CO2red,N2Ored,
         cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,TC_kgNO3,DC_kgSED,TC_kgSED,DC_MgBio,TC_MgBio,DC_enPot,TC_enPot,
         DC_MgCO2,TC_MgCO2,DC_MgN2O,TC_MgN2O)

## crop acres = field acres
WCR_BIOraw <- read_csv("../data/raw/WCR_practiceSummary_BIOv2.csv") %>%
  mutate(practice = "WCR",
         pID = FBndID,
         IWAP = 0,
         INRS = "Rye cover crops",
         biomass = "rye",
         adjOCost = OpportunityCost,
         opArea_ha = opAcres*0.404686, # convert ac to ha
         bioYield_Mg = bioYield * 0.9072, ## convert tons to Mg
         cropArea_ha = cropAcres*0.404686, # convert ac to ha
         TotalCost = DirectCost,
         cpNO3ldkg = cpNO3load*0.453592, ## convert lb to kg
         cpNO3ldRedkg = cpNO3LoadReduced*0.453592, ## convert lb to kg
         cpSEDldkg = cpSEDloadlbs*0.453592, ## convert lb to kg
         cpSEDldRedkg = cpSEDLoadReduced*907.18, ## convert US tons to kg
         DC_kgNO3 = DirectCost / cpNO3ldRedkg,
         TC_kgNO3 = TotalCost / cpNO3ldRedkg,
         DC_kgSED = DirectCost / cpSEDldRedkg,
         TC_kgSED = TotalCost / cpSEDldRedkg,
         DC_MgCO2 = DirectCost / CO2red,
         TC_MgCO2 = TotalCost / CO2red,
         DC_MgN2O = DirectCost / N2Ored,
         TC_MgN2O = TotalCost / N2Ored,
         DC_MgBio = DirectCost / bioYield_Mg,
         TC_MgBio = TotalCost / bioYield_Mg,
         DC_enPot = DirectCost / energyPot,
         TC_enPot = TotalCost / energyPot) %>%
  select(MLRA,HUC12,pID,practice,opArea_ha,cropArea_ha,IWAP,INRS,DirectCost,OpportunityCost,
         adjOCost,TotalCost,FBndID,biomass,bioYield_Mg,energyPot,CO2red,N2Ored,
         cpNO3ldkg,cpNO3ldRedkg,cpSEDldkg,cpSEDldRedkg,
         DC_kgNO3,TC_kgNO3,DC_kgSED,TC_kgSED,DC_MgBio,TC_MgBio,DC_enPot,TC_enPot,
         DC_MgCO2,TC_MgCO2,DC_MgN2O,TC_MgN2O)

practSumBIO_df <- rbind(CBS_BIOraw, NRW_BIOraw, PCP_BIOraw, STB_BIOraw, WCR_BIOraw)
practSumBIO <- within(practSumBIO_df, MLRA[MLRA == 108] <- "108c")
practSumBIO <- within(practSumBIO, MLRA[MLRA == 115] <- "115c")

## Currently the acres in these tables represent the entire HUC12 area and not just the crop acres.
wsTotalNO3Load <- read_csv("../data/raw/wsTotalNO3Load.csv") %>%
  mutate(pollutant = "nitrate",
         loadkg = SUM_wsNO3load*0.453592) %>% # convert lb to kg
  select(HUC12,pollutant,loadkg)
         
wsTotalSEDLoad <- read_csv("../data/raw/wsTotalSEDLoad.csv") %>%
  mutate(pollutant = "sediment",
         loadkg = SUM_Mean_sed_lbs*0.453592) %>% # convert lb to kg
  select(HUC12,pollutant,loadkg)

wsLoad <- rbind(wsTotalNO3Load, wsTotalSEDLoad)


## field loads to estimate load by MLRA.
fbMgmt<- read_csv("../data/raw/fbNO3Load.csv") %>%
  mutate(NO3load_kgha = NO3loadAc*0.892179, # convert lb per ac to kg per ha
         Nrate_kgha = Nrate*0.892179, # convert lb per ac to kg per ha
         hectares = Acres * 0.404686) %>% # convert ac per ha
  select(MLRA,FBndID,isAG,hectares,inSup,GenLU,CropRotatn,Nrate_kgha,NO3load_kgha)

fbSieversRoute <-  read_csv("../data/raw/fbSieversRoutes.csv") %>%
  mutate(FBndID = trimws(sub("^([^-]+)-.*$", "\\1", Name),which="right")) %>%
  select(FBndID,Total_TruckTravelTime,Total_Kilometers)
  
fbNO3Load <- read_csv("../data/raw/fbNO3Load.csv") %>%
  mutate(pollutant = "nitrate",
         hectares = Acres*0.404686, # convert ac per ha
         loadkg = (Acres*NO3loadAc)*0.453592) %>% # convert lb to kg
  select(MLRA,FBndID,isAG,hectares,inSup,pollutant,loadkg)
         
fbSEDLoad <- read_csv("../data/raw/fbSEDLoad.csv") %>%
  mutate(pollutant = "sediment",
         hectares = Acres*0.404686, # convert ac per ha
         loadkg = Mean_sed_lbs*0.453592) %>% # convert lb to kg
  select(MLRA,FBndID,isAG,hectares,inSup,pollutant,loadkg)

fbLoad <- rbind(fbNO3Load, fbSEDLoad) %>%
  drop_na()


## Dataframe check
#head(practSum)
#head(wsLoad)
summary(practSumBIO)
unique(practSumBIO$MLRA)
#summary(wsLoad)

```

```{r explore_df, dependson="create_df"}
practMLRA_counts <- practSumBIO %>%
         group_by(MLRA, practice) %>%
         summarize(hectares = sum(opArea_ha), 
                   n = n(), .groups = "drop")

bioMLRA_counts <- practSumBIO %>%
         group_by(biomass) %>%
         summarize(hectares = sum(bioYield_Mg), 
                   n = n(), .groups = "drop")

practHUC12_counts <- practSumBIO %>%
         group_by(HUC12, practice) %>%
         summarize(hectares = sum(opArea_ha),
                   n = n(), .groups = "drop")

bioHUC12_counts <- practSumBIO %>%
         group_by(HUC12, biomass) %>%
         summarize(hectares = sum(opArea_ha),
                   n = n(), .groups = "drop")

bioSup_counts <- practSumBIO %>%
         group_by(biomass) %>%
         summarize(hectares = sum(opArea_ha),
                   yield = sum(bioYield_Mg),
                   n = n(), .groups = "drop")

bioSup_counts <- practSumBIO %>%
         reframe(hectares = sum(opArea_ha),
                   yield = sum(bioYield_Mg),
                   energy = sum(energyPot),
                   NO3 = sum(cpNO3ldRedkg),
                   Sed = sum(cpSEDldRedkg),
                   CO2 = sum(CO2red),
                   N2O = sum(N2Ored),
                   DC = sum(DirectCost),
                   TC = sum(TotalCost),
                   OC = sum(TotalCost) - sum(DirectCost))

IWAPHUC12_counts <- practSumBIO %>%
  filter(IWAP >0) %>%
  group_by(HUC12,IWAP) %>%
  summarize(hectares = sum(opArea_ha),
          n = n(), .groups = "drop")
         
```

```{r mean_data, dependson = "create_soilpad"}
## How much is it going to cost to realize the INRS? How much to achieve wildlife goals?
practMLRA_CostSumBIOno3 <- practSumBIO %>% drop_na(cpNO3ldkg) %>%
  filter(cpSEDldRedkg >= 0) %>%
  group_by(MLRA, INRS) %>%
  summarize(sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC  = round(mean(DirectCost, na.rm = TRUE),0),
            minDC = round(min(DirectCost),0),
            maxDC = round(max(DirectCost),0),
            meanOC  = round(mean(adjOCost, na.rm = TRUE),0),
            minOC = round(min(adjOCost),0),
            maxOC = round(max(adjOCost),0),
            meanTC  = round(mean(TotalCost, na.rm = TRUE),0),
            minTC = round(min(TotalCost),0),
            maxTC = round(max(TotalCost),0),
            meanDC_kgNO3  = mean(DC_kgNO3, na.rm = TRUE),
            minDC_kgNO3 = min(DC_kgNO3, na.rm = TRUE),
            maxDC_kgNO3 = max(DC_kgNO3, na.rm = TRUE),
            meanTC_kgNO3 = mean(TC_kgNO3, na.rm = TRUE),
            minTC_kgNO3 = min(TC_kgNO3, na.rm = TRUE),
            maxTC_kgNO3 = max(TC_kgNO3, na.rm = TRUE),
            opAcres = sum(opArea_ha),
            n       = n(),
            .groups = "drop")

write_csv(practMLRA_CostSumBIOno3,"practMLRA_CostSumBIOno3.csv")

practMLRA_CostSumBIOsed <- practSumBIO %>% drop_na(cpSEDldkg) %>% filter(DC_kgSED > 0) %>%
  filter(cpSEDldRedkg >= 0) %>%
  group_by(MLRA, INRS) %>%
  summarize(sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC  = round(mean(DirectCost, na.rm = TRUE),0),
            minDC = round(min(DirectCost),0),
            maxDC = round(max(DirectCost),0),
            meanOC  = round(mean(adjOCost, na.rm = TRUE),0),
            minOC = round(min(adjOCost),0),
            maxOC = round(max(adjOCost),0),
            meanTC  = round(mean(TotalCost, na.rm = TRUE),0),
            minTC = round(min(TotalCost),0),
            maxTC = round(max(TotalCost),0),
            meanDC_kgSed  = mean(DC_kgSED, na.rm = TRUE),
            minDC_kgSED = min(DC_kgSED, na.rm = TRUE),
            maxDC_kgSED = max(DC_kgSED, na.rm = TRUE),
            meanDC_kgSED  = mean(TC_kgSED, na.rm = TRUE),
            minDC_kgSED = min(TC_kgSED, na.rm = TRUE),
            maxDC_kgSED = max(TC_kgSED, na.rm = TRUE),
            opAcres = sum(opArea_ha),
            n       = n(),
            .groups = "drop")

write_csv(practMLRA_CostSumBIOsed,"practMLRA_CostSumBIOsed.csv")


## Which HUC12 should we start with?
practHUC12_CostSumBIOno3 <- practSumBIO %>% drop_na(cpNO3ldkg) %>%
  filter(cpSEDldRedkg >= 0) %>%
  group_by(HUC12) %>%
  summarize(sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC  = round(mean(DirectCost, na.rm = TRUE),0),
            minDC = round(min(DirectCost),0),
            maxDC = round(max(DirectCost),0),
            meanOC  = round(mean(adjOCost, na.rm = TRUE),0),
            minOC = round(min(adjOCost),0),
            maxOC = round(max(adjOCost),0),
            meanTC  = round(mean(TotalCost, na.rm = TRUE),0),
            minTC = round(min(TotalCost),0),
            maxTC = round(max(TotalCost),0),
            sumCO2red = sum(CO2red),
            meanDCredCO2  = mean(DC_MgCO2, na.rm = TRUE),
            minDCredCO2 = min(DC_MgCO2, na.rm = TRUE),
            maxDCredCO2 = max(DC_MgCO2, na.rm = TRUE),
            meanTCredCO2 = mean(TC_MgCO2, na.rm = TRUE),
            minTCredCO2 = min(TC_MgCO2, na.rm = TRUE),
            maxTCredCO2 = max(TC_MgCO2, na.rm = TRUE),
            sumN2Ored = sum(N2Ored),
            meanDCredN2O  = mean(DC_MgN2O, na.rm = TRUE),
            minDCredN2O = min(DC_MgN2O, na.rm = TRUE),
            maxDCredN2O = max(DC_MgN2O, na.rm = TRUE),
            meanTCredN2O = mean(TC_MgN2O, na.rm = TRUE),
            minTCredN2O = min(TC_MgN2O, na.rm = TRUE),
            maxTCredN2O = max(TC_MgN2O, na.rm = TRUE),
            sumcpNO3ldRedkg = sum(cpNO3ldRedkg, na.rm = TRUE),
            meanDCredNO3  = mean(DC_kgNO3, na.rm = TRUE),
            minDCredNO3 = min(DC_kgNO3, na.rm = TRUE),
            maxDCredNO3 = max(DC_kgNO3, na.rm = TRUE),
            meanTCredNO3 = mean(TC_kgNO3, na.rm = TRUE),
            minTCredNO3 = min(TC_kgNO3, na.rm = TRUE),
            maxTCredNO3 = max(TC_kgNO3, na.rm = TRUE),
            sum_opArea_ha = sum(opArea_ha),
            n       = n(),
            .groups = "drop")

write_csv(practHUC12_CostSumBIOno3,"practHUC12_CostSumBIOno3.csv")

practHUC12_CostSumBIOsed <- practSumBIO %>% drop_na(cpSEDldkg) %>% filter(DC_kgSED > 0) %>%
  filter(cpSEDldRedkg >= 0) %>%
  group_by(HUC12) %>%
  summarize(sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC  = round(mean(DirectCost, na.rm = TRUE),0),
            minDC = round(min(DirectCost),0),
            maxDC = round(max(DirectCost),0),
            meanOC  = round(mean(adjOCost, na.rm = TRUE),0),
            minOC = round(min(adjOCost),0),
            maxOC = round(max(adjOCost),0),
            meanTC  = round(mean(TotalCost, na.rm = TRUE),0),
            minTC = round(min(TotalCost),0),
            maxTC = round(max(TotalCost),0),
            sumCO2red = sum(CO2red),
            meanDCredCO2  = mean(DC_MgCO2, na.rm = TRUE),
            minDCredCO2 = min(DC_MgCO2, na.rm = TRUE),
            maxDCredCO2 = max(DC_MgCO2, na.rm = TRUE),
            meanTCredCO2 = mean(TC_MgCO2, na.rm = TRUE),
            minTCredCO2 = min(TC_MgCO2, na.rm = TRUE),
            maxTCredCO2 = max(TC_MgCO2, na.rm = TRUE),
            sumN2Ored = sum(N2Ored),
            meanDCredN2O  = mean(DC_MgN2O, na.rm = TRUE),
            minDCredN2O = min(DC_MgN2O, na.rm = TRUE),
            maxDCredN2O = max(DC_MgN2O, na.rm = TRUE),
            meanTCredN2O = mean(TC_MgN2O, na.rm = TRUE),
            minTCredN2O = min(TC_MgN2O, na.rm = TRUE),
            maxTCredN2O = max(TC_MgN2O, na.rm = TRUE),
            sumcpSEDldRedkg = sum(cpSEDldRedkg, na.rm = TRUE),
            meanDCredSED  = mean(DC_kgSED, na.rm = TRUE),
            minDCredSED = min(DC_kgSED, na.rm = TRUE),
            maxDCredSED = max(DC_kgSED, na.rm = TRUE),
            meanTCredSED = mean(TC_kgSED, na.rm = TRUE),
            minTCredSED = min(TC_kgSED, na.rm = TRUE),
            maxTCredSED = max(TC_kgSED, na.rm = TRUE),
            sum_opArea_ha = sum(opArea_ha),
            n       = n(),
            .groups = "drop")

write_csv(practHUC12_CostSumBIOsed,"practHUC12_CostSumBIOsed.csv")

# How much will it cost to achieve IWAP?
practIWAP_CostSumBIO <- practSumBIO %>% filter(IWAP == 1) %>%
  filter(cpSEDldRedkg >= 0) %>%
  group_by(MLRA) %>%
  summarize(sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC  = round(mean(DirectCost, na.rm = TRUE),0),
            minDC = round(min(DirectCost),0),
            maxDC = round(max(DirectCost),0),
            meanOC  = round(mean(adjOCost, na.rm = TRUE),0),
            minOC = round(min(adjOCost),0),
            maxOC = round(max(adjOCost),0),
            meanTC  = round(mean(TotalCost, na.rm = TRUE),0),
            minTC = round(min(TotalCost),0),
            maxTC = round(max(TotalCost),0),
            opAcres = sum(opArea_ha),
            n       = n(),
            .groups = "drop")

write_csv(practIWAP_CostSumBIO,"practIWAP_CostSumBIO.csv")

```

```{r explore_df, dependson="create_df"}

DC_kgNO3confintBIOHUC12 <- practSumBIO %>%
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  reframe(mean = mean(DC_kgNO3, na.rm=TRUE),
            median = median(DC_kgNO3, na.rm = TRUE),
            n = length(DC_kgNO3),
            sd = sd(DC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgNO3, na.rm = TRUE),
            max = max(DC_kgNO3, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

#the better way to describe this is visually. map of watersheds. symbolized by hectares of land impacts and labeled with cost-effectivness per rye and prairie

TC_kgNO3confintBIOHUC12 <- practSumBIO %>%
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  reframe(mean = mean(TC_kgNO3, na.rm=TRUE),
            median = median(TC_kgNO3, na.rm = TRUE),
            n = length(TC_kgNO3),
            sd = sd(TC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgNO3, na.rm = TRUE),
            max = max(TC_kgNO3, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

DC_kgSEDconfintBIOHUC12 <- practSumBIO %>% 
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  summarize(mean = mean(DC_kgSED, na.rm=TRUE),
            median = median(DC_kgSED, na.rm = TRUE),
            n = length(DC_kgSED),
            sd = sd(DC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgSED, na.rm = TRUE),
            max = max(DC_kgSED, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)


TC_kgSEDconfintBIOHUC12 <- practSumBIO %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_kgSED, na.rm=TRUE),
            median = median(TC_kgSED, na.rm = TRUE),
            n = length(TC_kgSED),
            sd = sd(TC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgSED, na.rm = TRUE),
            max = max(TC_kgSED, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

DC_MgCO2confintBIOHUC12 <- practSumBIO %>% 
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  summarize(mean = mean(DC_MgCO2, na.rm=TRUE),
            median = median(DC_MgCO2, na.rm = TRUE),
            n = length(DC_MgCO2),
            sd = sd(DC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgCO2, na.rm = TRUE),
            max = max(DC_MgCO2, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)


TC_MgCO2confintBIOHUC12 <- practSumBIO %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgCO2, na.rm=TRUE),
            median = median(TC_MgCO2, na.rm = TRUE),
            n = length(TC_MgCO2),
            sd = sd(TC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgCO2, na.rm = TRUE),
            max = max(TC_MgCO2, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

DC_MgN2OconfintBIOHUC12 <- practSumBIO %>% 
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  summarize(mean = mean(DC_MgN2O, na.rm=TRUE),
            median = median(DC_MgN2O, na.rm = TRUE),
            n = length(DC_MgN2O),
            sd = sd(DC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgN2O, na.rm = TRUE),
            max = max(DC_MgN2O, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)


TC_MgN2OconfintBIOHUC12 <- practSumBIO %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgN2O, na.rm=TRUE),
            median = median(TC_MgN2O, na.rm = TRUE),
            n = length(TC_MgN2O),
            sd = sd(TC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgN2O, na.rm = TRUE),
            max = max(TC_MgN2O, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

DC_MgBioconfintBIOHUC12 <- practSumBIO %>% 
  filter(cpSEDldRedkg >= 0) %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  summarize(mean = mean(DC_MgBio, na.rm=TRUE),
            median = median(DC_MgBio, na.rm = TRUE),
            n = length(DC_MgBio),
            sd = sd(DC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgBio, na.rm = TRUE),
            max = max(DC_MgBio, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)


TC_MgBioconfintBIOHUC12 <- practSumBIO %>%
  #group_by(MLRA,INRS) %>%
  group_by(HUC12,biomass) %>%
  #group_by(HUC12) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgBio, na.rm=TRUE),
            median = median(TC_MgBio, na.rm = TRUE),
            n = length(TC_MgBio),
            sd = sd(TC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgBio, na.rm = TRUE),
            max = max(TC_MgBio, na.rm = TRUE)) %>%
  select(HUC12,biomass,mean,lb,ub)

write_csv(DC_kgNO3confintBIOHUC12,"../data/tidy/DC_kgNO3confintBIOHUC12.csv")
write_csv(TC_kgNO3confintBIOHUC12,"../data/tidy/TC_kgNO3confintBIOHUC12.csv")
write_csv(DC_kgSEDconfintBIOHUC12,"../data/tidy/DC_kgSEDconfintBIOHUC12.csv")
write_csv(TC_kgSEDconfintBIOHUC12,"../data/tidy/TC_kgSEDconfintBIOHUC12.csv")
write_csv(DC_MgN2OconfintBIOHUC12,"../data/tidy/DC_MgN2OconfintBIOHUC12.csv")
write_csv(TC_MgN2OconfintBIOHUC12,"../data/tidy/TC_MgN2OconfintBIOHUC12.csv")
write_csv(DC_MgCO2confintBIOHUC12,"../data/tidy/DC_MgCO2confintBIOHUC12.csv")
write_csv(TC_MgCO2confintBIOHUC12,"../data/tidy/TC_MgCO2confintBIOHUC12.csv")
write_csv(DC_MgBioconfintBIOHUC12,"../data/tidy/DC_MgBioconfintBIOHUC12.csv")
write_csv(TC_MgBioconfintBIOHUC12,"../data/tidy/TC_MgBioconfintBIOHUC12.csv")

```

```{r explore_df, dependson="create_df"}
## Supplyshed by MLRA average and confidence intervals of outcomes
DC_kgNO3confintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_kgNO3, na.rm=TRUE),
            median = median(DC_kgNO3, na.rm = TRUE),
            n = length(DC_kgNO3),
            sd = sd(DC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgNO3),
            max = max(DC_kgNO3))%>%
  select(INRS,mean,lb,ub)

TC_kgNO3confintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_kgNO3, na.rm=TRUE),
            median = median(TC_kgNO3, na.rm = TRUE),
            n = length(TC_kgNO3),
            sd = sd(TC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgNO3),
            max = max(TC_kgNO3))%>%
  select(INRS,mean,lb,ub)

DC_kgSEDconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_kgSED, na.rm=TRUE),
            median = median(DC_kgSED, na.rm = TRUE),
            n = length(DC_kgSED),
            sd = sd(DC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgSED),
            max = max(DC_kgSED))%>%
  select(INRS,mean,lb,ub)

TC_kgSEDconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_kgSED, na.rm=TRUE),
            median = median(TC_kgSED, na.rm = TRUE),
            n = length(TC_kgSED),
            sd = sd(TC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgSED),
            max = max(TC_kgSED))%>%
  select(INRS,mean,lb,ub)

DC_MgCO2confintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgCO2, na.rm=TRUE),
            median = median(DC_MgCO2, na.rm = TRUE),
            n = length(DC_MgCO2),
            sd = sd(DC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgCO2),
            max = max(DC_MgCO2))%>%
  select(INRS,mean,lb,ub)

TC_MgCO2confintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgCO2, na.rm=TRUE),
            median = median(TC_MgCO2, na.rm = TRUE),
            n = length(TC_MgCO2),
            sd = sd(TC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgCO2),
            max = max(TC_MgCO2))%>%
  select(INRS,mean,lb,ub)

DC_MgN2OconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgN2O, na.rm=TRUE),
            median = median(DC_MgN2O, na.rm = TRUE),
            n = length(DC_MgN2O),
            sd = sd(DC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgN2O),
            max = max(DC_MgN2O))%>%
  select(INRS,mean,lb,ub)

TC_MgN2OconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgN2O, na.rm=TRUE),
            median = median(TC_MgN2O, na.rm = TRUE),
            n = length(TC_MgN2O),
            sd = sd(TC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgN2O),
            max = max(TC_MgN2O))%>%
  select(INRS,mean,lb,ub)


DC_MgBioconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgBio, na.rm=TRUE),
            median = median(DC_MgBio, na.rm = TRUE),
            n = length(DC_MgBio),
            sd = sd(DC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgBio),
            max = max(DC_MgBio))%>%
  select(INRS,mean,lb,ub)

TC_MgBioconfintBIOSup <- practSumBIO %>%
  group_by(INRS) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgBio, na.rm=TRUE),
            median = median(TC_MgBio, na.rm = TRUE),
            n = length(TC_MgBio),
            sd = sd(TC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgBio),
            max = max(TC_MgBio))%>%
  select(INRS,mean,lb,ub)

write_csv(DC_kgNO3confintBIOSup,"../data/tidy/DC_kgNO3confintBIOSup.csv")
write_csv(TC_kgNO3confintBIOSup,"../data/tidy/TC_kgNO3confintBIOSup.csv")
write_csv(DC_kgSEDconfintBIOSup,"../data/tidy/DC_kgSEDconfintBIOSup.csv")
write_csv(TC_kgSEDconfintBIOSup,"../data/tidy/TC_kgSEDconfintBIOSup.csv")
write_csv(DC_MgN2OconfintBIOSup,"../data/tidy/DC_MgN2OconfintBIOSup.csv")
write_csv(TC_MgN2OconfintBIOSup,"../data/tidy/TC_MgN2OconfintBIOSup.csv")
write_csv(DC_MgCO2confintBIOSup,"../data/tidy/DC_MgCO2confintBIOSup.csv")
write_csv(TC_MgCO2confintBIOSup,"../data/tidy/TC_MgCO2confintBIOSup.csv")
write_csv(DC_MgBioconfintBIOSup,"../data/tidy/DC_MgBioconfintBIOSup.csv")
write_csv(TC_MgBioconfintBIOSup,"../data/tidy/TC_MgBioconfintBIOSup.csv")

```


```{r explore_df, dependson="create_df"}
## Supplyshed by MLRA average and confidence intervals of outcomes
DC_kgNO3confintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_kgNO3, na.rm=TRUE),
            median = median(DC_kgNO3, na.rm = TRUE),
            n = length(DC_kgNO3),
            sd = sd(DC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgNO3),
            max = max(DC_kgNO3))%>%
  select(INRS,MLRA,mean,lb,ub)

TC_kgNO3confintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_kgNO3, na.rm=TRUE),
            median = median(TC_kgNO3, na.rm = TRUE),
            n = length(TC_kgNO3),
            sd = sd(TC_kgNO3, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgNO3),
            max = max(TC_kgNO3))%>%
  select(INRS,MLRA,mean,lb,ub)

DC_kgSEDconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_kgSED, na.rm=TRUE),
            median = median(DC_kgSED, na.rm = TRUE),
            n = length(DC_kgSED),
            sd = sd(DC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_kgSED),
            max = max(DC_kgSED))%>%
  select(INRS,MLRA,mean,lb,ub)

TC_kgSEDconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_kgSED, na.rm=TRUE),
            median = median(TC_kgSED, na.rm = TRUE),
            n = length(TC_kgSED),
            sd = sd(TC_kgSED, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_kgSED),
            max = max(TC_kgSED))%>%
  select(INRS,MLRA,mean,lb,ub)

DC_MgCO2confintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgCO2, na.rm=TRUE),
            median = median(DC_MgCO2, na.rm = TRUE),
            n = length(DC_MgCO2),
            sd = sd(DC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgCO2),
            max = max(DC_MgCO2))%>%
  select(INRS,MLRA,mean,lb,ub)

TC_MgCO2confintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgCO2, na.rm=TRUE),
            median = median(TC_MgCO2, na.rm = TRUE),
            n = length(TC_MgCO2),
            sd = sd(TC_MgCO2, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgCO2),
            max = max(TC_MgCO2))%>%
  select(INRS,MLRA,mean,lb,ub)

DC_MgN2OconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgN2O, na.rm=TRUE),
            median = median(DC_MgN2O, na.rm = TRUE),
            n = length(DC_MgN2O),
            sd = sd(DC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgN2O),
            max = max(DC_MgN2O))%>%
  select(INRS,MLRA,mean,lb,ub)

TC_MgN2OconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgN2O, na.rm=TRUE),
            median = median(TC_MgN2O, na.rm = TRUE),
            n = length(TC_MgN2O),
            sd = sd(TC_MgN2O, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgN2O),
            max = max(TC_MgN2O))%>%
  select(INRS,MLRA,mean,lb,ub)


DC_MgBioconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(DC_MgBio, na.rm=TRUE),
            median = median(DC_MgBio, na.rm = TRUE),
            n = length(DC_MgBio),
            sd = sd(DC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(DC_MgBio),
            max = max(DC_MgBio))%>%
  select(INRS,MLRA,mean,lb,ub)

TC_MgBioconfintBIOMLRA <- practSumBIO %>%
  group_by(INRS,MLRA) %>%
  filter(cpSEDldRedkg >= 0) %>%
  summarize(mean = mean(TC_MgBio, na.rm=TRUE),
            median = median(TC_MgBio, na.rm = TRUE),
            n = length(TC_MgBio),
            sd = sd(TC_MgBio, na.rm = TRUE),
            se = sd / sqrt(n),
            t.score = qt(p= 0.05/2, df = (n-1), lower.tail = F),
            margErr = t.score*se,
            lb = mean - margErr,
            ub = mean + margErr,
            min = min(TC_MgBio),
            max = max(TC_MgBio))%>%
  select(INRS,MLRA,mean,lb,ub)

write_csv(DC_kgNO3confintBIOMLRA,"../data/tidy/DC_kgNO3confintBIOMLRA.csv")
write_csv(TC_kgNO3confintBIOMLRA,"../data/tidy/TC_kgNO3confintBIOMLRA.csv")
write_csv(DC_kgSEDconfintBIOMLRA,"../data/tidy/DC_kgSEDconfintBIOMLRA.csv")
write_csv(TC_kgSEDconfintBIOMLRA,"../data/tidy/TC_kgSEDconfintBIOMLRA.csv")
write_csv(DC_MgN2OconfintBIOMLRA,"../data/tidy/DC_MgN2OconfintBIOMLRA.csv")
write_csv(TC_MgN2OconfintBIOMLRA,"../data/tidy/TC_MgN2OconfintBIOMLRA.csv")
write_csv(DC_MgCO2confintBIOMLRA,"../data/tidy/DC_MgCO2confintBIOMLRA.csv")
write_csv(TC_MgCO2confintBIOMLRA,"../data/tidy/TC_MgCO2confintBIOMLRA.csv")
write_csv(DC_MgBioconfintBIOMLRA,"../data/tidy/DC_MgBioconfintBIOMLRA.csv")
write_csv(TC_MgBioconfintBIOMLRA,"../data/tidy/TC_MgBioconfintBIOMLRA.csv")

```



Compare costs. It might be interesting to visually have a side-by-side comparison of direct, 
total, and opportunity costs. 
```{r explore_df, dependson="create_df"}
practSum_TC_kgSED <- filter(practSumBIO, TC_kgSED < 1000)

fbLoadSumStat <- fbLoad %>% 
  filter(loadkg > 0) %>%
  group_by(MLRA, pollutant) %>%
  summarise(n=n(),
            sumLoadkg = sum(loadkg),
            meankg = mean(loadkg), 
            sdkg=sd(loadkg),
            sekg=(sdkg/sqrt(n)))

ggplot(fbLoadSumStat, aes(MLRA, meankg, fill=pollutant)) +
  geom_bar(stat = "identity",position=position_dodge()) +
  geom_errorbar(aes(x=MLRA, ymin=meankg-sekg, ymax=meankg+sekg), width=0.4, 
                position = position_dodge(0.9)) +
  scale_fill_manual(values=c("#999999", "#999123")) +
  ggtitle("Mean Pollutant Load Per Field by MLRA (SE plotted)") +
  xlab("MLRA") +
  ylab("Pollutant Load (kg)")

ggplot(fbLoadSumStat, aes(MLRA, (sumLoadkg), fill=pollutant)) +
  geom_bar(stat = "identity",position=position_dodge()) +
  scale_fill_manual(values=c("#999999", "#999123")) +
  ggtitle("Total Pollutant Load Per Field by MLRA") +
  xlab("MLRA") +
  ylab("Pollutant Load (kg)")
##make a graph comparing direct, opportunity, and total costs per practice

```

Look at bioyield and transportation costs
```{r mean_data, dependson = "create_soilpad"}
## How much is it going to cost to realize the INRS? How much to achieve wildlife goals?
bio_CostSumNO3 <- practSumBIO %>% drop_na(cpNO3ldkg) %>%
  group_by(FBndID, biomass) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            sumbioYield = sum(bioYield_Mg),
            sumEnergyPot = sum(energyPot),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC_kgNO3  = mean(DC_kgNO3, na.rm = TRUE),
            minDC_kgNO3 = min(DC_kgNO3, na.rm = TRUE),
            maxDC_kgNO3 = max(DC_kgNO3, na.rm = TRUE),
            meanTC_kgNO3 = mean(TC_kgNO3, na.rm = TRUE),
            minTC_kgNO3 = min(TC_kgNO3, na.rm = TRUE),
            maxTC_kgNO3 = max(TC_kgNO3, na.rm = TRUE),
            .groups = "drop")

bio_CostSumSED <- practSumBIO %>% drop_na(cpSEDldkg) %>%
  group_by(FBndID, biomass) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            sumbioYield = sum(bioYield_Mg),
            sumEnergyPot = sum(energyPot),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            meanDC_kgSED  = mean(DC_kgSED, na.rm = TRUE),
            minDC_kgSED = min(DC_kgSED, na.rm = TRUE),
            maxDC_kgSED = max(DC_kgSED, na.rm = TRUE),
            meanTC_kgSED  = mean(TC_kgSED, na.rm = TRUE),
            minTC_kgSED = min(TC_kgSED, na.rm = TRUE),
            maxTC_kgSED = max(TC_kgSED, na.rm = TRUE),
            .groups = "drop")

envOutcome_CostSum <- practSumBIO %>%
  #group_by(INRS,IWAP,HUC12) %>%
  group_by(FBndID) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            MLRA = max(MLRA),
            HUC12 = max(HUC12),
            IWAP = max(IWAP),
            practice = list(unique(INRS)),
            ## Bio yield summary
            sum_BioMg = sum(bioYield_Mg),
            #BioMg_med = median(bioYield_Mg, na.rm = TRUE),
            #Q1_BioMg = quantile(bioYield_Mg, probs = c(0.25)),
            #Q3_BioMg = quantile(bioYield_Mg, probs = c(0.75)),
            #BioTC_Mg_med = median(TC_MgBio, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            
            ## Energy potential summary
            sumEnergyPot = sum(energyPot),
            #engPot_med = median(energyPot, na.rm = TRUE),
            #Q1_engPot = quantile(energyPot, probs = c(0.25)),
            #Q3_engPot = quantile(energyPot, probs = c(0.75)),
            #engPotTC_med = median(TC_enPot, na.rm = TRUE),
            #Q1TC_enPot = quantile(TC_enPot, probs = c(0.25)),
            #Q3TC_enPot = quantile(TC_enPot, probs = c(0.75)),
            
            ## Cost summary per field
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            
            ## CO2 summary
            sumCO2 = sum(CO2red),
            #CO2red_med = median(CO2red, na.rm = TRUE),
            #Q1_CO2red = quantile(CO2red, probs = c(0.25)),
            #Q3_CO2red = quantile(CO2red, probs = c(0.75)),
            #CO2TC_Mg_med = median(TC_MgCO2, na.rm=TRUE),
            #Q1_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.25)),
            #Q3_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.75)),
            
            ## N2O summary
            sumN2Ored = sum(N2Ored),
            #N2Ored_med = median(N2Ored, na.rm=TRUE),
            #Q1_N2Ored = quantile(N2Ored, probs = c(0.25)),
            #Q3_N2Ored = quantile(N2Ored, probs = c(0.75)),
            #N2OTC_Mg_med = median(TC_MgN2O, na.rm=TRUE),
            #Q1_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.25)),
            #Q3_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.75)),
            
            # NO3 load summary
            sumNO3red = sum(cpNO3ldRedkg, na.rm = TRUE),
            #NO3red_med = median(cpNO3ldRedkg, na.rm = TRUE),
            #Q1_NO3red = quantile(cpNO3ldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3red = quantile(cpNO3ldRedkg, probs = c(0.75), na.rm = TRUE),
            #NO3TC_kg_med = median(TC_kgNO3, na.rm = TRUE),
            #Q1_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            sumSEDred = sum(cpSEDldRedkg, na.rm = TRUE))
            #SEDred_med = median(cpSEDldRedkg, na.rm = TRUE),
            #Q1_SEDred = quantile(cpSEDldRedkg, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDred = quantile(cpSEDldRedkg, probs = c(0.75), na.rm = TRUE),
            #SEDTC_kg_med = median(TC_kgSED, na.rm = TRUE),
            #Q1_SEDTC_kg = quantile(TC_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTC_kg = quantile(TC_kgSED, probs = c(0.75), na.rm = TRUE))#,
            #.groups = "drop")
write_csv(envOutcome_CostSum,"envOutcome_byField.csv")

travel_envOutcomes <- full_join(envOutcome_CostSum, fbSieversRoute)

travel_Sum <- travel_envOutcomes %>%
  group_by(HUC12) %>%
  summarize(sum_hectares = sum(opArea_ha),
            sum_bioYield = sum(sumbioYield),
            sum_enPot = sum(sumEnergyPot),
            mean_time = mean(Total_TruckTravelTime),
            mean_dist = mean(Total_Kilometers))

write_csv(travel_Sum,"bioHUC12.csv")

## QA/QC for transportation routes to ensure number of routes and locations match
## use spatial join to add FBndID to STB and NRW
# travelNA <- routes %>% filter(is.na(Total_TruckTravelTime))
# removeRoute <- bio_travelNO3 %>% filter(is.na(IWAP))
# routes <- bio_travelNO3 %>% drop_na(IWAP)
# write_csv(routes,"finalRoutes.csv")
# write_csv(travelNA, "missingRoutes.csv")

envOutcome_CostSum <- practSumBIO %>%
  group_by(HUC12) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            MLRA = max(MLRA),
            HUC12 = max(HUC12),
            sumbioYield = sum(bioYield_Mg),
            sumEnergyPot = sum(energyPot),
            sumDC = sum(DirectCost),
            sumOC = sum(adjOCost),
            sumTC = sum(TotalCost),
            sumCO2red = sum(CO2red),
            sumN2ored = sum(N2Ored),
            sumcpNO3LoadReduced = sum(cpNO3ldRedkg, na.rm = TRUE)/1000,
            sumcpSEDLoadReduced = sum(cpSEDldRedkg, na.rm = TRUE)/1000)
            #.groups = "drop")

envOutcome_BioSum <- practSumBIO %>%
  group_by(HUC12,biomass) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            MLRA = max(MLRA),
            sumbioYield = sum(bioYield_Mg),
            sumEnergyPot = sum(energyPot))
            #.groups = "drop")

envOutcome_WildSum <- practSumBIO %>%
  group_by(HUC12,IWAP) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n())
            #.groups = "drop")


write_csv(envOutcome_CostSum,"../data/tidy/envOutcome_CostSumHUC12.csv")
write_csv(envOutcome_BioSum,"../data/tidy/envOutcome_BioSumHUC12.csv")
write_csv(envOutcome_WildSum,"../data/tidy/envOutcome_WildSumHUC12.csv")

GHGsum <- practSumBIO %>%
  group_by(MLRA) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            MLRA = max(MLRA),
            sumCO2red = sum(CO2red),
            minCO2Red = min(CO2red, na.rm=TRUE),
            maxCO2Red = max(CO2red, na.rm=TRUE),
            sumN2Ored = sum(N2Ored),
            minN2ORed = min(N2Ored, na.rm=TRUE),
            maxN2ORed = max(N2Ored, na.rm=TRUE),
            sumcpNO3LoadReduced = sum(cpNO3ldRedkg, na.rm = TRUE),
            minNO3Red = min(cpNO3ldRedkg, na.rm=TRUE),
            maxNO3Red = max(cpNO3ldRedkg, na.rm=TRUE),
            sumcpSEDLoadReduced = sum(cpSEDldRedkg, na.rm = TRUE),
            minSEDRed = min(cpSEDldRedkg, na.rm = TRUE),
            maxSEDRed = max(cpSEDldRedkg, na.rm=TRUE),
            IWAP = max(IWAP),
            .groups = "drop")

practIWAP_Sum <- practSumBIO %>%
  filter(IWAP == 1) %>%
  group_by(HUC12) %>%
  summarize(n       = n(),
            hectares = sum(opArea_ha),
            mean_ha = mean(opArea_ha),
            sd = sd(opArea_ha),
            se=(sd/sqrt(n)),
            min_ha = min(opArea_ha),
            max_ha = max(opArea_ha),
            .groups = "drop")


envOutcome_FB <- envOutcome_CostSum %>%
  #group_by(INRS,IWAP,HUC12) %>%
  summarize(opArea_ha = sum(opArea_ha),
            n       = n(),
            #MLRA = max(MLRA),
            #HUC12 = max(HUC12),
            #IWAP = max(IWAP),
            #practice = list(unique(INRS)),
            ## Bio yield summary
            #sum_BioMg = sum(bioYield_Mg),
            BioMg_mean = mean(sum_BioMg, na.rm = TRUE),
            BioMg_se = sd(sum_BioMg) / sqrt(n),
            BioMg_med = median(sum_BioMg, na.rm = TRUE),
            Q1_BioMg = quantile(sum_BioMg, probs = c(0.25)),
            Q3_BioMg = quantile(sum_BioMg, probs = c(0.75)),
            #BioTC_Mg_med = median(TC_MgBio, na.rm = TRUE),
            #Q1TC_MgBio = quantile(TC_MgBio, probs = c(0.25)),
            #Q3TC_MgBio = quantile(TC_MgBio, probs = c(0.75)),
            
            ## Energy potential summary
            #sumEnergyPot = sum(energyPot),
            engPot_mean = mean(sumEnergyPot, na.rm = TRUE),
            engPot_se = sd(sumEnergyPot) / sqrt(n),
            engPot_med = median(sumEnergyPot, na.rm = TRUE),
            Q1_engPot = quantile(sumEnergyPot, probs = c(0.25)),
            Q3_engPot = quantile(sumEnergyPot, probs = c(0.75)),
            #engPotTC_med = median(TC_enPot, na.rm = TRUE),
            #Q1TC_enPot = quantile(TC_enPot, probs = c(0.25)),
            #Q3TC_enPot = quantile(TC_enPot, probs = c(0.75)),
            
            ## Cost summary per field
            #sumDC = sum(DirectCost),
            #sumOC = sum(adjOCost),
            #sumTC = sum(TotalCost),
            
            ## CO2 summary
            #sumCO2 = sum(CO2red),
            CO2red_mean = median(sumCO2, na.rm = TRUE),
            CO2red_sd = sd(sumCO2) / sqrt(n),
            CO2red_med = median(sumCO2, na.rm = TRUE),
            Q1_CO2red = quantile(sumCO2, probs = c(0.25)),
            Q3_CO2red = quantile(sumCO2, probs = c(0.75)),
            #CO2TC_Mg_med = median(TC_MgCO2, na.rm=TRUE),
            #Q1_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.25)),
            #Q3_CO2TC_Mg = quantile(TC_MgCO2, probs = c(0.75)),
            
            ## N2O summary
            #sumN2Ored = sum(N2Ored),
            N2Ored_mean = mean(sumN2Ored, na.rm=TRUE),
            N2Ored_se = sd(sumN2Ored) / sqrt(n),
            N2Ored_med = median(sumN2Ored, na.rm=TRUE),
            Q1_N2Ored = quantile(sumN2Ored, probs = c(0.25)),
            Q3_N2Ored = quantile(sumN2Ored, probs = c(0.75)),
            #N2OTC_Mg_med = median(TC_MgN2O, na.rm=TRUE),
            #Q1_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.25)),
            #Q3_N2OTC_Mg = quantile(TC_MgN2O, probs = c(0.75)),
            
            # NO3 load summary
            #sumNO3red = sum(cpNO3ldRedkg, na.rm = TRUE),
            NO3red_mean = mean(sumNO3red, na.rm = TRUE),
            NO3red_sd = sd(sumNO3red) / sqrt(n),
            NO3red_med = median(sumNO3red, na.rm = TRUE),
            Q1_NO3red = quantile(sumNO3red, probs = c(0.25), na.rm = TRUE),
            Q3_NO3red = quantile(sumNO3red, probs = c(0.75), na.rm = TRUE),
            #NO3TC_kg_med = median(TC_kgNO3, na.rm = TRUE),
            #Q1_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.25), na.rm = TRUE),
            #Q3_NO3TC_kg = quantile(TC_kgNO3, probs = c(0.75), na.rm = TRUE),
            
            ## Sediment load summary
            #sumSEDred = sum(cpSEDldRedkg, na.rm = TRUE))
            SEDred_mean = mean(sumSEDred, na.rm = TRUE),
            SEDred_se = sd(sumSEDred) / sqrt(n),
            SEDred_med = median(sumSEDred, na.rm = TRUE),
            Q1_SEDred = quantile(sumSEDred, probs = c(0.25), na.rm = TRUE),
            Q3_SEDred = quantile(sumSEDred, probs = c(0.75), na.rm = TRUE))
            #SEDTC_kg_med = median(TC_kgSED, na.rm = TRUE)
            #Q1_SEDTC_kg = quantile(TC_kgSED, probs = c(0.25), na.rm = TRUE),
            #Q3_SEDTC_kg = quantile(TC_kgSED, probs = c(0.75), na.rm = TRUE))#,
            #.groups = "drop")
```